/* Generated by MyraPad at 05.06.2020 22:34:38 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

namespace Myra.Graphics2D.UI.ColorPicker
{
	partial class ColorPickerPanel: VerticalStackPanel
	{
		private void BuildUI()
		{
			_colorWheel = new Image();
			_colorWheel.Id = "_colorWheel";

			_hsPicker = new Image();
			_hsPicker.BorderThickness = new Thickness(1);
			_hsPicker.Padding = new Thickness(4);
			_hsPicker.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_hsPicker.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_hsPicker.Enabled = false;
			_hsPicker.Background = new SolidBrush("#FFFFFFFF");
			_hsPicker.Border = new SolidBrush("#000000");
			_hsPicker.Id = "_hsPicker";

			var panel1 = new Panel();
			panel1.Width = 147;
			panel1.Height = 147;
			panel1.Widgets.Add(_colorWheel);
			panel1.Widgets.Add(_hsPicker);

			_gradient = new Image();
			_gradient.Width = 10;
			_gradient.Height = 147;
			_gradient.BorderThickness = new Thickness(1);
			_gradient.Border = new SolidBrush("#000000");
			_gradient.Id = "_gradient";

			_vPicker = new Image();
			_vPicker.Margin = new Thickness(0, 1);
			_vPicker.BorderThickness = new Thickness(1);
			_vPicker.Padding = new Thickness(4);
			_vPicker.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_vPicker.Enabled = false;
			_vPicker.Background = new SolidBrush("#FFFFFFFF");
			_vPicker.Border = new SolidBrush("#000000");
			_vPicker.Id = "_vPicker";

			var panel2 = new Panel();
			panel2.Widgets.Add(_gradient);
			panel2.Widgets.Add(_vPicker);

			_colorBackground = new Image();
			_colorBackground.Width = 40;
			_colorBackground.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_colorBackground.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_colorBackground.GridColumnSpan = 3;
			_colorBackground.Background = new SolidBrush("#FFFFFFFF");
			_colorBackground.Id = "_colorBackground";

			_colorDisplay = new Image();
			_colorDisplay.Width = 40;
			_colorDisplay.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_colorDisplay.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_colorDisplay.GridColumnSpan = 3;
			_colorDisplay.Id = "_colorDisplay";

			var label1 = new Label();
			label1.Text = "RGB";
			label1.GridRow = 1;

			_inputRGB = new TextBox();
			_inputRGB.GridColumn = 1;
			_inputRGB.GridRow = 1;
			_inputRGB.GridColumnSpan = 2;
			_inputRGB.Id = "_inputRGB";

			var label2 = new Label();
			label2.Text = "HSV";
			label2.GridRow = 2;

			_inputHSV = new TextBox();
			_inputHSV.GridColumn = 1;
			_inputHSV.GridRow = 2;
			_inputHSV.GridColumnSpan = 2;
			_inputHSV.Id = "_inputHSV";

			var label3 = new Label();
			label3.Text = "HEX";
			label3.GridRow = 3;

			_inputHEX = new TextBox();
			_inputHEX.GridColumn = 1;
			_inputHEX.GridRow = 3;
			_inputHEX.GridColumnSpan = 2;
			_inputHEX.Id = "_inputHEX";

			var label4 = new Label();
			label4.Text = "Alpha";
			label4.GridRow = 4;

			_inputAlpha = new TextBox();
			_inputAlpha.GridColumn = 2;
			_inputAlpha.GridRow = 4;
			_inputAlpha.Id = "_inputAlpha";

			_sliderAlpha = new HorizontalSlider();
			_sliderAlpha.Maximum = 255;
			_sliderAlpha.Height = 21;
			_sliderAlpha.GridColumn = 1;
			_sliderAlpha.GridRow = 4;
			_sliderAlpha.Id = "_sliderAlpha";

			_saveColor = new TextButton();
			_saveColor.Text = "Save Color";
			_saveColor.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			_saveColor.GridRow = 5;
			_saveColor.GridColumnSpan = 3;
			_saveColor.Id = "_saveColor";

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 6;
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 60,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 40,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			grid1.Widgets.Add(_colorBackground);
			grid1.Widgets.Add(_colorDisplay);
			grid1.Widgets.Add(label1);
			grid1.Widgets.Add(_inputRGB);
			grid1.Widgets.Add(label2);
			grid1.Widgets.Add(_inputHSV);
			grid1.Widgets.Add(label3);
			grid1.Widgets.Add(_inputHEX);
			grid1.Widgets.Add(label4);
			grid1.Widgets.Add(_inputAlpha);
			grid1.Widgets.Add(_sliderAlpha);
			grid1.Widgets.Add(_saveColor);

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			horizontalStackPanel1.Widgets.Add(panel1);
			horizontalStackPanel1.Widgets.Add(panel2);
			horizontalStackPanel1.Widgets.Add(grid1);

			_userColors = new Grid();
			_userColors.ColumnSpacing = 8;
			_userColors.RowSpacing = 8;
			_userColors.GridSelectionMode = Myra.Graphics2D.UI.GridSelectionMode.Cell;
			_userColors.Height = 80;
			_userColors.Padding = new Thickness(4);
			_userColors.Id = "_userColors";

			
			Spacing = 8;
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Width = 450;
			Padding = new Thickness(10, 0, 10, 5);
			Widgets.Add(horizontalStackPanel1);
			Widgets.Add(_userColors);
		}

		
		public Image _colorWheel;
		public Image _hsPicker;
		public Image _gradient;
		public Image _vPicker;
		public Image _colorBackground;
		public Image _colorDisplay;
		public TextBox _inputRGB;
		public TextBox _inputHSV;
		public TextBox _inputHEX;
		public TextBox _inputAlpha;
		public HorizontalSlider _sliderAlpha;
		public TextButton _saveColor;
		public Grid _userColors;
	}
}