/* Generated by Myra UI Editor at 11/16/2017 2:38:36 AM */

using Myra.Editor.UI.File;
using Myra.Graphics2D;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.UI.ColorPicker;

namespace Myra.Samples.AllWidgets
{
	public partial class AllWidgets : Grid
	{
		public AllWidgets()
		{
			BuildUI();

			_button.Image = new Drawable(DefaultAssets.UISpritesheet["icon-star"]);
			_blueButton.Image = new Drawable(DefaultAssets.UISpritesheet["icon-star"]);
			_imageButton.Image = new Drawable(DefaultAssets.UISpritesheet["icon-star-outline"]);

			_button.Up += (sender, args) =>
			{
				var debugWindow = new FileDialog(FileDialogMode.OpenFile);
				debugWindow.ShowModal(Desktop);
			};

			_blueButton.Up += (sender, args) =>
			{
				var debugWindow = new FileDialog(FileDialogMode.SaveFile);
				debugWindow.ShowModal(Desktop);
			};

			_textButton.Up += (sender, args) =>
			{
				var debugWindow = new ColorPickerDialog();
				debugWindow.ShowModal(Desktop);

				debugWindow.Closed += (s, a) =>
				{
					if (!debugWindow.Result)
					{
						return;
					}

					_textButtonLabel.TextColor = debugWindow.Color;
				};
			};

			_imageButton.Up += (sender, args) =>
			{
				var debugWindow = new DebugOptionsDialog();
				debugWindow.ShowModal(Desktop);
			};

			_menuItemAbout.Selected += (sender, args) =>
			{
				var messageBox = Dialog.CreateMessageBox("AllWidgets", "Myra AllWidgets Sample " + MyraEnvironment.Version);
				messageBox.ShowModal(Desktop);
			};

			var tree = new Tree
			{
				HasRoot = false,
				GridPositionX = 1,
				GridPositionY = 11
			};
			var node1 = tree.AddSubNode("node1");
			var node2 = node1.AddSubNode("node2");
			var node3 = node2.AddSubNode("node3");
			node3.AddSubNode("node4");
			node3.AddSubNode("node5");
			node2.AddSubNode("node6");
			_gridRight.Widgets.Add(tree);
		}
	}
}