/* Generated by Myra UI Editor at 22.10.2018 22:34:28 */
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;

namespace Myra.Samples.AllWidgets
{
	partial class AllWidgets
	{
		private void BuildUI()
		{
			_menuItemNew = new MenuItem();
			_menuItemNew.Id = "_menuItemNew";
			_menuItemNew.Text = "&New";

			_menuItemOpen = new MenuItem();
			_menuItemOpen.Id = "_menuItemOpen";
			_menuItemOpen.Text = "&Open";

			_menuItemSave = new MenuItem();
			_menuItemSave.Id = "_menuItemSave";
			_menuItemSave.Text = "&Save";

			_menuItemSaveAs = new MenuItem();
			_menuItemSaveAs.Id = "_menuItemSaveAs";
			_menuItemSaveAs.Text = "Save &As...";

			var menuSeparator1 = new MenuSeparator();

			_menuItemQuit = new MenuItem();
			_menuItemQuit.Id = "_menuItemQuit";
			_menuItemQuit.Text = "&Quit";

			var menuItem1 = new MenuItem();
			menuItem1.Id = "";
			menuItem1.Text = "&File";
			menuItem1.Items.Add(_menuItemNew);
			menuItem1.Items.Add(_menuItemOpen);
			menuItem1.Items.Add(_menuItemSave);
			menuItem1.Items.Add(_menuItemSaveAs);
			menuItem1.Items.Add(menuSeparator1);
			menuItem1.Items.Add(_menuItemQuit);

			_menuItemCopy = new MenuItem();
			_menuItemCopy.Id = "_menuItemCopy";
			_menuItemCopy.Text = "&Copy";

			_menuItemPaste = new MenuItem();
			_menuItemPaste.Id = "_menuItemPaste";
			_menuItemPaste.Text = "&Paste";

			var menuSeparator2 = new MenuSeparator();

			_menuItemUndo = new MenuItem();
			_menuItemUndo.Id = "_menuItemUndo";
			_menuItemUndo.Text = "&Undo";

			_menuItemRedo = new MenuItem();
			_menuItemRedo.Id = "_menuItemRedo";
			_menuItemRedo.Text = "&Redo";

			var menuItem2 = new MenuItem();
			menuItem2.Id = "";
			menuItem2.Text = "&Edit";
			menuItem2.Items.Add(_menuItemCopy);
			menuItem2.Items.Add(_menuItemPaste);
			menuItem2.Items.Add(menuSeparator2);
			menuItem2.Items.Add(_menuItemUndo);
			menuItem2.Items.Add(_menuItemRedo);

			_menuItemAbout = new MenuItem();
			_menuItemAbout.Id = "_menuItemAbout";
			_menuItemAbout.Text = "&About";

			var menuItem3 = new MenuItem();
			menuItem3.Id = "";
			menuItem3.Text = "&Help";
			menuItem3.Items.Add(_menuItemAbout);

			var horizontalMenu1 = new HorizontalMenu();
			horizontalMenu1.DrawLinesColor = Color.White;
			horizontalMenu1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			horizontalMenu1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			horizontalMenu1.Items.Add(menuItem1);
			horizontalMenu1.Items.Add(menuItem2);
			horizontalMenu1.Items.Add(menuItem3);

			var textBlock1 = new TextBlock();
			textBlock1.Text = "Button:";
			textBlock1.Id = "";

			_button = new Button();
			_button.Text = "Open File";
			_button.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_button.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_button.Id = "_button";
			_button.PaddingLeft = 8;
			_button.PaddingRight = 8;
			_button.GridPositionX = 1;

			var textBlock2 = new TextBlock();
			textBlock2.Text = "Blue Button:";
			textBlock2.Id = "";
			textBlock2.GridPositionY = 1;

			_blueButton = new Button("blue");
			_blueButton.Text = "Save File";
			_blueButton.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_blueButton.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_blueButton.Id = "_blueButton";
			_blueButton.PaddingLeft = 8;
			_blueButton.PaddingRight = 8;
			_blueButton.GridPositionX = 1;
			_blueButton.GridPositionY = 1;

			_textButtonLabel = new TextBlock();
			_textButtonLabel.Text = "Text Button:";
			_textButtonLabel.Id = "_textButtonLabel";
			_textButtonLabel.GridPositionY = 2;

			_textButton = new TextButton();
			_textButton.Text = "Choose Color";
			_textButton.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_textButton.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_textButton.Id = "_textButton";
			_textButton.PaddingLeft = 8;
			_textButton.PaddingRight = 8;
			_textButton.GridPositionX = 1;
			_textButton.GridPositionY = 2;

			var textBlock3 = new TextBlock();
			textBlock3.Text = "Image Button:";
			textBlock3.Id = "";
			textBlock3.GridPositionY = 3;

			_imageButton = new ImageButton();
			_imageButton.ImageVisible = true;
			_imageButton.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_imageButton.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_imageButton.Id = "_imageButton";
			_imageButton.PaddingLeft = 8;
			_imageButton.PaddingRight = 8;
			_imageButton.GridPositionX = 1;
			_imageButton.GridPositionY = 3;

			var checkBox1 = new CheckBox();
			checkBox1.Text = "This is checkbox";
			checkBox1.ImageWidthHint = 10;
			checkBox1.ImageHeightHint = 10;
			checkBox1.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			checkBox1.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			checkBox1.GridPositionY = 4;
			checkBox1.GridSpanX = 2;

			var textBlock4 = new TextBlock();
			textBlock4.Text = "Horizontal Slider:";
			textBlock4.Id = "";
			textBlock4.GridPositionY = 5;

			var horizontalSlider1 = new HorizontalSlider();
			horizontalSlider1.Maximum = 100;
			horizontalSlider1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			horizontalSlider1.GridPositionX = 1;
			horizontalSlider1.GridPositionY = 5;

			var textBlock5 = new TextBlock();
			textBlock5.Text = "Combo Box:";
			textBlock5.GridPositionY = 6;

			var listItem1 = new ListItem();
			listItem1.Id = "";
			listItem1.Text = "Red";
			listItem1.Color = Color.Red;

			var listItem2 = new ListItem();
			listItem2.Text = "Green";
			listItem2.Color = Color.Lime;

			var listItem3 = new ListItem();
			listItem3.Text = "Blue";
			listItem3.Color = new Color
			{
				B = 255,
				G = 128,
				A = 255,
			};

			var comboBox1 = new ComboBox();
			comboBox1.WidthHint = 200;
			comboBox1.GridPositionX = 1;
			comboBox1.GridPositionY = 6;
			comboBox1.Items.Add(listItem1);
			comboBox1.Items.Add(listItem2);
			comboBox1.Items.Add(listItem3);

			var textBlock6 = new TextBlock();
			textBlock6.Text = "Text Field:";
			textBlock6.GridPositionY = 7;

			var textField1 = new TextField();
			textField1.Text = "";
			textField1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			textField1.GridPositionX = 1;
			textField1.GridPositionY = 7;
			textField1.ClipToBounds = true;
			textField1.CanFocus = true;

			var textBlock7 = new TextBlock();
			textBlock7.Text = "Spin Button:";
			textBlock7.GridPositionY = 8;

			var spinButton1 = new SpinButton();
			spinButton1.Value = 0;
			spinButton1.DrawLinesColor = Color.White;
			spinButton1.WidthHint = 100;
			spinButton1.GridPositionX = 1;
			spinButton1.GridPositionY = 8;

			var textBlock8 = new TextBlock();
			textBlock8.Text = "List Box:";
			textBlock8.GridPositionY = 9;

			var listItem4 = new ListItem();
			listItem4.Text = "Red";
			listItem4.Color = Color.Red;

			var listItem5 = new ListItem();
			listItem5.Text = "Green";
			listItem5.Color = Color.Lime;

			var listItem6 = new ListItem();
			listItem6.Text = "Blue";
			listItem6.Color = Color.Blue;

			var listBox1 = new ListBox();
			listBox1.DrawLinesColor = Color.White;
			listBox1.WidthHint = 200;
			listBox1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			listBox1.GridPositionX = 1;
			listBox1.GridPositionY = 9;
			listBox1.Items.Add(listItem4);
			listBox1.Items.Add(listItem5);
			listBox1.Items.Add(listItem6);

			var textBlock9 = new TextBlock();
			textBlock9.Text = "Vertical Menu:";
			textBlock9.GridPositionY = 10;

			var menuItem4 = new MenuItem();
			menuItem4.Id = "";
			menuItem4.Text = "Start New Game";

			var menuItem5 = new MenuItem();
			menuItem5.Id = "";
			menuItem5.Text = "Options";

			var menuItem6 = new MenuItem();
			menuItem6.Id = "";
			menuItem6.Text = "Quit";

			var verticalMenu1 = new VerticalMenu();
			verticalMenu1.DrawLinesColor = Color.White;
			verticalMenu1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			verticalMenu1.GridPositionX = 1;
			verticalMenu1.GridPositionY = 10;
			verticalMenu1.Items.Add(menuItem4);
			verticalMenu1.Items.Add(menuItem5);
			verticalMenu1.Items.Add(menuItem6);

			var textBlock10 = new TextBlock();
			textBlock10.Text = "Tree";
			textBlock10.GridPositionY = 11;

			_gridRight = new Grid();
			_gridRight.DrawLinesColor = Color.White;
			_gridRight.ColumnSpacing = 8;
			_gridRight.RowSpacing = 8;
			_gridRight.ColumnsProportions.Add(new Grid.Proportion());
			_gridRight.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.Id = "_gridRight";
			_gridRight.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_gridRight.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_gridRight.Widgets.Add(textBlock1);
			_gridRight.Widgets.Add(_button);
			_gridRight.Widgets.Add(textBlock2);
			_gridRight.Widgets.Add(_blueButton);
			_gridRight.Widgets.Add(_textButtonLabel);
			_gridRight.Widgets.Add(_textButton);
			_gridRight.Widgets.Add(textBlock3);
			_gridRight.Widgets.Add(_imageButton);
			_gridRight.Widgets.Add(checkBox1);
			_gridRight.Widgets.Add(textBlock4);
			_gridRight.Widgets.Add(horizontalSlider1);
			_gridRight.Widgets.Add(textBlock5);
			_gridRight.Widgets.Add(comboBox1);
			_gridRight.Widgets.Add(textBlock6);
			_gridRight.Widgets.Add(textField1);
			_gridRight.Widgets.Add(textBlock7);
			_gridRight.Widgets.Add(spinButton1);
			_gridRight.Widgets.Add(textBlock8);
			_gridRight.Widgets.Add(listBox1);
			_gridRight.Widgets.Add(textBlock9);
			_gridRight.Widgets.Add(verticalMenu1);
			_gridRight.Widgets.Add(textBlock10);

			var scrollPane1 = new ScrollPane();
			scrollPane1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			scrollPane1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			scrollPane1.ClipToBounds = true;
			scrollPane1.CanFocus = true;
			scrollPane1.Child = _gridRight;

			var textBlock11 = new TextBlock();
			textBlock11.Text = "Vertical Slider:";

			var verticalSlider1 = new VerticalSlider();
			verticalSlider1.Maximum = 100;
			verticalSlider1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			verticalSlider1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			verticalSlider1.GridPositionY = 1;

			var grid1 = new Grid();
			grid1.DrawLinesColor = Color.White;
			grid1.RowSpacing = 8;
			grid1.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.RowsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			grid1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			grid1.Widgets.Add(textBlock11);
			grid1.Widgets.Add(verticalSlider1);

			var textBlock12 = new TextBlock();
			textBlock12.Text = "Progress Bars:";

			_horizontalProgressBar = new HorizontalProgressBar();
			_horizontalProgressBar.Maximum = 100;
			_horizontalProgressBar.DrawLinesColor = Color.White;
			_horizontalProgressBar.Id = "_horizontalProgressBar";
			_horizontalProgressBar.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_horizontalProgressBar.GridPositionY = 1;

			_verticalProgressBar = new VerticalProgressBar();
			_verticalProgressBar.Maximum = 100;
			_verticalProgressBar.DrawLinesColor = Color.White;
			_verticalProgressBar.Id = "_verticalProgressBar";
			_verticalProgressBar.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_verticalProgressBar.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_verticalProgressBar.GridPositionY = 2;

			var grid2 = new Grid();
			grid2.DrawLinesColor = Color.White;
			grid2.RowSpacing = 8;
			grid2.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid2.RowsProportions.Add(new Grid.Proportion());
			grid2.RowsProportions.Add(new Grid.Proportion());
			grid2.RowsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			grid2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			grid2.GridPositionY = 2;
			grid2.Widgets.Add(textBlock12);
			grid2.Widgets.Add(_horizontalProgressBar);
			grid2.Widgets.Add(_verticalProgressBar);

			var verticalSplitPane1 = new VerticalSplitPane();
			verticalSplitPane1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			verticalSplitPane1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			verticalSplitPane1.GridPositionX = 2;
			verticalSplitPane1.Widgets.Add(grid1);
			verticalSplitPane1.Widgets.Add(grid2);

			var horizontalSplitPane1 = new HorizontalSplitPane();
			horizontalSplitPane1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			horizontalSplitPane1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			horizontalSplitPane1.GridPositionY = 1;
			horizontalSplitPane1.Widgets.Add(scrollPane1);
			horizontalSplitPane1.Widgets.Add(verticalSplitPane1);

			
			DrawLinesColor = Color.White;
			RowSpacing = 8;
			RowsProportions.Add(new Grid.Proportion());
			RowsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			Id = "Root";
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			Widgets.Add(horizontalMenu1);
			Widgets.Add(horizontalSplitPane1);
		}

		
		public MenuItem _menuItemNew;
		public MenuItem _menuItemOpen;
		public MenuItem _menuItemSave;
		public MenuItem _menuItemSaveAs;
		public MenuItem _menuItemQuit;
		public MenuItem _menuItemCopy;
		public MenuItem _menuItemPaste;
		public MenuItem _menuItemUndo;
		public MenuItem _menuItemRedo;
		public MenuItem _menuItemAbout;
		public Button _button;
		public Button _blueButton;
		public TextBlock _textButtonLabel;
		public TextButton _textButton;
		public ImageButton _imageButton;
		public Grid _gridRight;
		public HorizontalProgressBar _horizontalProgressBar;
		public VerticalProgressBar _verticalProgressBar;
	}
}