/* Generated by MyraPad at 06.01.2020 23:00:03 */
using Myra.Assets;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace Myra.Samples.DebugConsole
{
	partial class DebugPanel: VerticalStackPanel
	{
		private void BuildUI()
		{
			var menuItem1 = new MenuItem();
			menuItem1.Text = "Add &Orc";

			var menuItem2 = new MenuItem();
			menuItem2.Text = "Add &Peasant";

			var menuItem3 = new MenuItem();
			menuItem3.Text = "Add &Knight";

			var menuItem4 = new MenuItem();
			menuItem4.Text = "Add &Priest";

			var menuItem5 = new MenuItem();
			menuItem5.Text = "Add &Wizard";

			var menuItem6 = new MenuItem();
			menuItem6.Text = "&Units";
			menuItem6.Items.Add(menuItem1);
			menuItem6.Items.Add(menuItem2);
			menuItem6.Items.Add(menuItem3);
			menuItem6.Items.Add(menuItem4);
			menuItem6.Items.Add(menuItem5);

			var menuItem7 = new MenuItem();
			menuItem7.Text = "Add 10000 &Gold";

			var menuItem8 = new MenuItem();
			menuItem8.Text = "Add 10000 &Wood";

			var menuItem9 = new MenuItem();
			menuItem9.Text = "&Operations";
			menuItem9.Items.Add(menuItem7);
			menuItem9.Items.Add(menuItem8);

			var horizontalMenu1 = new HorizontalMenu();
			horizontalMenu1.Items.Add(menuItem6);
			horizontalMenu1.Items.Add(menuItem9);

			var label1 = new Label();
			label1.Text = "Command:";

			var textBox1 = new TextBox();

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			horizontalStackPanel1.Widgets.Add(label1);
			horizontalStackPanel1.Widgets.Add(textBox1);

			_buttonHideDebug = new TextButton();
			_buttonHideDebug.Text = "Hide Debug Panel";
			_buttonHideDebug.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_buttonHideDebug.Id = "_buttonHideDebug";

			
			Spacing = 8;
			Height = 300;
			Widgets.Add(horizontalMenu1);
			Widgets.Add(horizontalStackPanel1);
			Widgets.Add(_buttonHideDebug);
		}

		
		public TextButton _buttonHideDebug;
	}
}