/* Generated by MyraPad at 10/23/2023 9:53:16 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Myra.Samples.DebugConsole
{
	partial class GamePanel: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Game Screen";
			label1.Top = 100;
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var radioButton1 = new RadioButton();
			radioButton1.Text = "Radio 1";

			var radioButton2 = new RadioButton();
			radioButton2.Text = "Radio 2";

			var radioButton3 = new RadioButton();
			radioButton3.Text = "Radio 3";

			var radioButton4 = new RadioButton();
			radioButton4.Text = "Radio 4";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Top = 50;
			horizontalStackPanel1.Widgets.Add(radioButton1);
			horizontalStackPanel1.Widgets.Add(radioButton2);
			horizontalStackPanel1.Widgets.Add(radioButton3);
			horizontalStackPanel1.Widgets.Add(radioButton4);

			var textButton1 = new TextButton();
			textButton1.Text = "Button 1";

			var textButton2 = new TextButton();
			textButton2.Text = "Button 2";

			var textButton3 = new TextButton();
			textButton3.Text = "Button 3";

			var textButton4 = new TextButton();
			textButton4.Text = "Button 4";

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Spacing = 8;
			horizontalStackPanel2.Top = 300;
			horizontalStackPanel2.Widgets.Add(textButton1);
			horizontalStackPanel2.Widgets.Add(textButton2);
			horizontalStackPanel2.Widgets.Add(textButton3);
			horizontalStackPanel2.Widgets.Add(textButton4);

			_buttonDebugPanel = new TextButton();
			_buttonDebugPanel.Text = "Show Debug Panel";
			_buttonDebugPanel.Id = "_buttonDebugPanel";

			_buttonModalDebugPanel = new TextButton();
			_buttonModalDebugPanel.Text = "Show Debug Panel Modal";
			_buttonModalDebugPanel.Id = "_buttonModalDebugPanel";

			var horizontalStackPanel3 = new HorizontalStackPanel();
			horizontalStackPanel3.Spacing = 8;
			horizontalStackPanel3.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			horizontalStackPanel3.Widgets.Add(_buttonDebugPanel);
			horizontalStackPanel3.Widgets.Add(_buttonModalDebugPanel);

			
			Widgets.Add(label1);
			Widgets.Add(horizontalStackPanel1);
			Widgets.Add(horizontalStackPanel2);
			Widgets.Add(horizontalStackPanel3);
		}

		
		public TextButton _buttonDebugPanel;
		public TextButton _buttonModalDebugPanel;
	}
}
