/* Generated by MyraPad at 9/8/2026 11:23:54 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Myra.Samples
{
	partial class MainForm: VerticalStackPanel
	{
		private void BuildUI()
		{
			_panelContainer = new ScrollViewer();
			_panelContainer.Id = "_panelContainer";
			StackPanel.SetProportionType(_panelContainer, Myra.Graphics2D.UI.ProportionType.Fill);

			var horizontalSeparator1 = new HorizontalSeparator();

			var label1 = new Label();
			label1.Text = "Text Scaling:";

			var label2 = new Label();
			label2.Text = "None";

			var label3 = new Label();
			label3.Text = "Supersampling";

			var label4 = new Label();
			label4.Text = "SDF";

			_comboTextScaling = new ComboView();
			_comboTextScaling.Id = "_comboTextScaling";
			Grid.SetColumn(_comboTextScaling, 1);
			_comboTextScaling.Widgets.Add(label2);
			_comboTextScaling.Widgets.Add(label3);
			_comboTextScaling.Widgets.Add(label4);

			var label5 = new Label();
			label5.Text = "Scale";
			label5.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Grid.SetRow(label5, 1);

			_sliderScale = new HorizontalSlider();
			_sliderScale.Minimum = 0.2f;
			_sliderScale.Maximum = 4;
			_sliderScale.Value = 1;
			_sliderScale.Width = 500;
			_sliderScale.Id = "_sliderScale";

			_labelScale = new Label();
			_labelScale.Text = "3";
			_labelScale.Id = "_labelScale";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			Grid.SetColumn(horizontalStackPanel1, 1);
			Grid.SetRow(horizontalStackPanel1, 1);
			horizontalStackPanel1.Widgets.Add(_sliderScale);
			horizontalStackPanel1.Widgets.Add(_labelScale);

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid1.Widgets.Add(label1);
			grid1.Widgets.Add(_comboTextScaling);
			grid1.Widgets.Add(label5);
			grid1.Widgets.Add(horizontalStackPanel1);

			_propertyGridParameters = new PropertyGrid();
			_propertyGridParameters.Id = "_propertyGridParameters";

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Spacing = 8;
			horizontalStackPanel2.Widgets.Add(grid1);
			horizontalStackPanel2.Widgets.Add(_propertyGridParameters);

			
			Widgets.Add(_panelContainer);
			Widgets.Add(horizontalSeparator1);
			Widgets.Add(horizontalStackPanel2);
		}

		
		private ScrollViewer _panelContainer;
		private ComboView _comboTextScaling;
		private HorizontalSlider _sliderScale;
		private Label _labelScale;
		private PropertyGrid _propertyGridParameters;
	}
}
