/* Generated by Myra UI Editor at 29.10.2018 0:23:01 */
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;

namespace Myra.Samples.CustomUIStylesheet
{
	partial class AllWidgets
	{
		private void BuildUI()
		{
			var textBlock1 = new TextBlock();
			textBlock1.Text = "Button:";
			textBlock1.Id = "";

			_button = new Button();
			_button.Text = "Button";
			_button.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_button.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_button.Id = "_button";
			_button.PaddingLeft = 8;
			_button.PaddingRight = 8;
			_button.GridPositionX = 1;

			_textButtonLabel = new TextBlock();
			_textButtonLabel.Text = "Text Button:";
			_textButtonLabel.Id = "_textButtonLabel";
			_textButtonLabel.GridPositionY = 1;

			_textButton = new TextButton();
			_textButton.Text = "Text Button";
			_textButton.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_textButton.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_textButton.Id = "_textButton";
			_textButton.PaddingLeft = 8;
			_textButton.PaddingRight = 8;
			_textButton.GridPositionX = 1;
			_textButton.GridPositionY = 1;

			var textBlock2 = new TextBlock();
			textBlock2.Text = "Image Button:";
			textBlock2.Id = "";
			textBlock2.GridPositionY = 2;

			_imageButton = new ImageButton();
			_imageButton.ImageVisible = true;
			_imageButton.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_imageButton.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_imageButton.Id = "_imageButton";
			_imageButton.PaddingLeft = 8;
			_imageButton.PaddingRight = 8;
			_imageButton.GridPositionX = 1;
			_imageButton.GridPositionY = 2;

			var checkBox1 = new CheckBox();
			checkBox1.Text = "This is checkbox";
			checkBox1.ImageWidthHint = 10;
			checkBox1.ImageHeightHint = 10;
			checkBox1.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			checkBox1.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			checkBox1.GridPositionY = 3;
			checkBox1.GridSpanX = 2;

			var textBlock3 = new TextBlock();
			textBlock3.Text = "Horizontal Slider:";
			textBlock3.Id = "";
			textBlock3.GridPositionY = 4;

			var horizontalSlider1 = new HorizontalSlider();
			horizontalSlider1.Maximum = 100;
			horizontalSlider1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			horizontalSlider1.GridPositionX = 1;
			horizontalSlider1.GridPositionY = 4;

			var textBlock4 = new TextBlock();
			textBlock4.Text = "Combo Box:";
			textBlock4.GridPositionY = 5;

			var listItem1 = new ListItem();
			listItem1.Id = "";
			listItem1.Text = "Item 1";

			var listItem2 = new ListItem();
			listItem2.Text = "Item 2";

			var listItem3 = new ListItem();
			listItem3.Text = "Item 3";

			var comboBox1 = new ComboBox();
			comboBox1.WidthHint = 200;
			comboBox1.GridPositionX = 1;
			comboBox1.GridPositionY = 5;
			comboBox1.Items.Add(listItem1);
			comboBox1.Items.Add(listItem2);
			comboBox1.Items.Add(listItem3);

			var textBlock5 = new TextBlock();
			textBlock5.Text = "Text Field:";
			textBlock5.GridPositionY = 6;

			var textField1 = new TextField();
			textField1.Text = "";
			textField1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			textField1.GridPositionX = 1;
			textField1.GridPositionY = 6;
			textField1.ClipToBounds = true;
			textField1.CanFocus = true;

			var textBlock6 = new TextBlock();
			textBlock6.Text = "List Box:";
			textBlock6.GridPositionY = 7;

			var listItem4 = new ListItem();
			listItem4.Text = "Item 1";

			var listItem5 = new ListItem();
			listItem5.Text = "Item 2";

			var listItem6 = new ListItem();
			listItem6.Text = "Item 3";

			var listBox1 = new ListBox();
			listBox1.DrawLinesColor = Color.White;
			listBox1.WidthHint = 200;
			listBox1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			listBox1.GridPositionX = 1;
			listBox1.GridPositionY = 7;
			listBox1.Items.Add(listItem4);
			listBox1.Items.Add(listItem5);
			listBox1.Items.Add(listItem6);

			var textBlock7 = new TextBlock();
			textBlock7.Text = "Tree";
			textBlock7.GridPositionY = 8;

			_gridRight = new Grid();
			_gridRight.DrawLinesColor = Color.White;
			_gridRight.ColumnSpacing = 8;
			_gridRight.RowSpacing = 8;
			_gridRight.ColumnsProportions.Add(new Grid.Proportion());
			_gridRight.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.Id = "_gridRight";
			_gridRight.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_gridRight.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_gridRight.Widgets.Add(textBlock1);
			_gridRight.Widgets.Add(_button);
			_gridRight.Widgets.Add(_textButtonLabel);
			_gridRight.Widgets.Add(_textButton);
			_gridRight.Widgets.Add(textBlock2);
			_gridRight.Widgets.Add(_imageButton);
			_gridRight.Widgets.Add(checkBox1);
			_gridRight.Widgets.Add(textBlock3);
			_gridRight.Widgets.Add(horizontalSlider1);
			_gridRight.Widgets.Add(textBlock4);
			_gridRight.Widgets.Add(comboBox1);
			_gridRight.Widgets.Add(textBlock5);
			_gridRight.Widgets.Add(textField1);
			_gridRight.Widgets.Add(textBlock6);
			_gridRight.Widgets.Add(listBox1);
			_gridRight.Widgets.Add(textBlock7);

			var scrollPane1 = new ScrollPane();
			scrollPane1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			scrollPane1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			scrollPane1.ClipToBounds = true;
			scrollPane1.CanFocus = true;
			scrollPane1.Child = _gridRight;

			var textBlock8 = new TextBlock();
			textBlock8.Text = "Vertical Slider:";

			var verticalSlider1 = new VerticalSlider();
			verticalSlider1.Maximum = 100;
			verticalSlider1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			verticalSlider1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			verticalSlider1.GridPositionY = 1;

			var grid1 = new Grid();
			grid1.DrawLinesColor = Color.White;
			grid1.RowSpacing = 8;
			grid1.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.RowsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			grid1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			grid1.Widgets.Add(textBlock8);
			grid1.Widgets.Add(verticalSlider1);

			var textBlock9 = new TextBlock();
			textBlock9.Text = "Progress Bars:";

			_horizontalProgressBar = new HorizontalProgressBar();
			_horizontalProgressBar.Maximum = 100;
			_horizontalProgressBar.DrawLinesColor = Color.White;
			_horizontalProgressBar.Id = "_horizontalProgressBar";
			_horizontalProgressBar.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_horizontalProgressBar.GridPositionY = 1;

			_verticalProgressBar = new VerticalProgressBar();
			_verticalProgressBar.Maximum = 100;
			_verticalProgressBar.DrawLinesColor = Color.White;
			_verticalProgressBar.Id = "_verticalProgressBar";
			_verticalProgressBar.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_verticalProgressBar.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_verticalProgressBar.GridPositionY = 2;

			var grid2 = new Grid();
			grid2.DrawLinesColor = Color.White;
			grid2.RowSpacing = 8;
			grid2.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid2.RowsProportions.Add(new Grid.Proportion());
			grid2.RowsProportions.Add(new Grid.Proportion());
			grid2.RowsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			grid2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			grid2.GridPositionY = 2;
			grid2.Widgets.Add(textBlock9);
			grid2.Widgets.Add(_horizontalProgressBar);
			grid2.Widgets.Add(_verticalProgressBar);

			var verticalSplitPane1 = new VerticalSplitPane();
			verticalSplitPane1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			verticalSplitPane1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			verticalSplitPane1.GridPositionX = 2;
			verticalSplitPane1.Widgets.Add(grid1);
			verticalSplitPane1.Widgets.Add(grid2);

			
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			GridPositionY = 1;
			Widgets.Add(scrollPane1);
			Widgets.Add(verticalSplitPane1);
		}

		
		public Button _button;
		public TextBlock _textButtonLabel;
		public TextButton _textButton;
		public ImageButton _imageButton;
		public Grid _gridRight;
		public HorizontalProgressBar _horizontalProgressBar;
		public VerticalProgressBar _verticalProgressBar;
	}
}