/* Generated by MyraPad at 6/3/2026 11:32:38 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Myra.Graphics2D.UI.File
{
	partial class FileDialog: Dialog
	{
		private void BuildUI()
		{
			var image1 = new Image();

			_buttonBack = new Button();
			_buttonBack.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_buttonBack.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_buttonBack.Id = "_buttonBack";
			_buttonBack.Content = image1;

			var image2 = new Image();

			_buttonForward = new Button();
			_buttonForward.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_buttonForward.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_buttonForward.Id = "_buttonForward";
			_buttonForward.Content = image2;

			_textFieldPath = new TextBox();
			_textFieldPath.Readonly = true;
			_textFieldPath.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_textFieldPath.Id = "_textFieldPath";
			StackPanel.SetProportionType(_textFieldPath, Myra.Graphics2D.UI.ProportionType.Fill);

			var image3 = new Image();

			_buttonParent = new Button();
			_buttonParent.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_buttonParent.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_buttonParent.Id = "_buttonParent";
			_buttonParent.Content = image3;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 4;
			horizontalStackPanel1.Widgets.Add(_buttonBack);
			horizontalStackPanel1.Widgets.Add(_buttonForward);
			horizontalStackPanel1.Widgets.Add(_textFieldPath);
			horizontalStackPanel1.Widgets.Add(_buttonParent);

			_listPlaces = new ListView();
			_listPlaces.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_listPlaces.ClipToBounds = true;
			_listPlaces.Id = "_listPlaces";

			_gridFiles = new Grid();
			_gridFiles.ColumnSpacing = 4;
			_gridFiles.RowSpacing = 4;
			
			_gridFiles.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});_gridFiles.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			_gridFiles.GridSelectionMode = Myra.Graphics2D.UI.GridSelectionMode.Row;
			_gridFiles.Id = "_gridFiles";

			_scrollPane = new ScrollViewer();
			_scrollPane.ShowHorizontalScrollBar = false;
			_scrollPane.Id = "_scrollPane";
			_scrollPane.Content = _gridFiles;

			_splitPane = new HorizontalSplitPane();
			_splitPane.Id = "_splitPane";
			StackPanel.SetProportionType(_splitPane, Myra.Graphics2D.UI.ProportionType.Fill);
			_splitPane.Widgets.Add(_listPlaces);
			_splitPane.Widgets.Add(_scrollPane);

			_textBlockFileName = new Label();
			_textBlockFileName.Text = "File name";
			_textBlockFileName.Id = "_textBlockFileName";

			_textFieldFileName = new TextBox();
			_textFieldFileName.Readonly = true;
			_textFieldFileName.Id = "_textFieldFileName";
			StackPanel.SetProportionType(_textFieldFileName, Myra.Graphics2D.UI.ProportionType.Fill);

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Spacing = 4;
			horizontalStackPanel2.Widgets.Add(_textBlockFileName);
			horizontalStackPanel2.Widgets.Add(_textFieldFileName);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 4;
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(_splitPane);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel2);

			
			Title = "Open File...";
			Left = 338;
			Top = 250;
			Width = 650;
			Height = 400;
			Content = verticalStackPanel1;
		}


		/// <summary>
		/// The back navigation button widget.
		/// </summary>
		public Button _buttonBack;
		/// <summary>
		/// The forward navigation button widget.
		/// </summary>
		public Button _buttonForward;
		/// <summary>
		/// The path text input field widget.
		/// </summary>
		public TextBox _textFieldPath;
		/// <summary>
		/// The parent directory button widget.
		/// </summary>
		public Button _buttonParent;
		/// <summary>
		/// The places/shortcuts list view widget.
		/// </summary>
		public ListView _listPlaces;
		/// <summary>
		/// The files grid widget.
		/// </summary>
		public Grid _gridFiles;
		/// <summary>
		/// The scroll pane containing the files grid.
		/// </summary>
		public ScrollViewer _scrollPane;
		/// <summary>
		/// The horizontal split pane widget.
		/// </summary>
		public HorizontalSplitPane _splitPane;
		/// <summary>
		/// The file name label widget.
		/// </summary>
		public Label _textBlockFileName;
		/// <summary>
		/// The file name text input field widget.
		/// </summary>
		public TextBox _textFieldFileName;
	}
}
