/* Generated by MyraPad at 06.01.2020 23:06:13 */
using Myra.Assets;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace Myra.Graphics2D.UI.File
{
	partial class FileDialog: Dialog
	{
		private void BuildUI()
		{
			_buttonBack = new ImageButton();
			_buttonBack.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_buttonBack.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_buttonBack.Id = "_buttonBack";

			_buttonForward = new ImageButton();
			_buttonForward.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_buttonForward.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_buttonForward.GridColumn = 1;
			_buttonForward.Id = "_buttonForward";

			_textFieldPath = new TextBox();
			_textFieldPath.Readonly = true;
			_textFieldPath.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_textFieldPath.GridColumn = 2;
			_textFieldPath.Id = "_textFieldPath";

			_buttonParent = new ImageButton();
			_buttonParent.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_buttonParent.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_buttonParent.GridColumn = 3;
			_buttonParent.Id = "_buttonParent";

			var grid1 = new Grid();
			grid1.ColumnSpacing = 4;
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.Widgets.Add(_buttonBack);
			grid1.Widgets.Add(_buttonForward);
			grid1.Widgets.Add(_textFieldPath);
			grid1.Widgets.Add(_buttonParent);

			_listBoxPlaces = new ListBox();
			_listBoxPlaces.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_listBoxPlaces.ClipToBounds = true;
			_listBoxPlaces.Id = "_listBoxPlaces";

			_gridFiles = new Grid();
			_gridFiles.ColumnSpacing = 4;
			_gridFiles.RowSpacing = 4;
			_gridFiles.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			_gridFiles.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			_gridFiles.GridSelectionMode = Myra.Graphics2D.UI.GridSelectionMode.Row;
			_gridFiles.Id = "_gridFiles";

			_scrollPane = new ScrollViewer();
			_scrollPane.ShowHorizontalScrollBar = false;
			_scrollPane.Id = "_scrollPane";
			_scrollPane.Content = _gridFiles;

			_splitPane = new HorizontalSplitPane();
			_splitPane.Id = "_splitPane";
			_splitPane.Widgets.Add(_listBoxPlaces);
			_splitPane.Widgets.Add(_scrollPane);

			_textBlockFileName = new Label();
			_textBlockFileName.Text = "File name";
			_textBlockFileName.Id = "_textBlockFileName";

			_textFieldFileName = new TextBox();
			_textFieldFileName.GridColumn = 1;
			_textFieldFileName.Id = "_textFieldFileName";

			var grid2 = new Grid();
			grid2.ColumnSpacing = 4;
			grid2.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid2.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid2.Widgets.Add(_textBlockFileName);
			grid2.Widgets.Add(_textFieldFileName);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 4;
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			verticalStackPanel1.Widgets.Add(grid1);
			verticalStackPanel1.Widgets.Add(_splitPane);
			verticalStackPanel1.Widgets.Add(grid2);

			
			Title = "Open File...";
			Left = 196;
			Top = 1;
			Width = 600;
			Height = 400;
			Content = verticalStackPanel1;
		}

		
		public ImageButton _buttonBack;
		public ImageButton _buttonForward;
		public TextBox _textFieldPath;
		public ImageButton _buttonParent;
		public ListBox _listBoxPlaces;
		public Grid _gridFiles;
		public ScrollViewer _scrollPane;
		public HorizontalSplitPane _splitPane;
		public Label _textBlockFileName;
		public TextBox _textFieldFileName;
	}
}