/* Generated by Myra UI Editor at 01.08.2018 2:11:23 */
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;

namespace Myra.Samples.FantasyMapGenerator.UI
{
	partial class MainForm
	{
		private void BuildUI()
		{
			var textBlock1 = new TextBlock();
			textBlock1.Text = "Width:";
			textBlock1.TextColor = Color.White;
			textBlock1.DisabledTextColor = new Color
			{
				B = 170,
				G = 170,
				R = 170,
				A = 255,
			};
			textBlock1.Id = "";

			_spinWidth = new SpinButton();
			_spinWidth.Value = 800;
			_spinWidth.DrawLinesColor = Color.White;
			_spinWidth.Id = "_spinWidth";
			_spinWidth.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_spinWidth.GridPositionX = 1;

			var textBlock2 = new TextBlock();
			textBlock2.Text = "Height";
			textBlock2.TextColor = Color.White;
			textBlock2.DisabledTextColor = new Color
			{
				B = 170,
				G = 170,
				R = 170,
				A = 255,
			};
			textBlock2.GridPositionY = 1;

			_spinHeight = new SpinButton();
			_spinHeight.Value = 600;
			_spinHeight.DrawLinesColor = Color.White;
			_spinHeight.Id = "_spinHeight";
			_spinHeight.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_spinHeight.GridPositionX = 1;
			_spinHeight.GridPositionY = 1;

			var textBlock3 = new TextBlock();
			textBlock3.Text = "Variability:";
			textBlock3.TextColor = Color.White;
			textBlock3.DisabledTextColor = new Color
			{
				B = 170,
				G = 170,
				R = 170,
				A = 255,
			};
			textBlock3.GridPositionY = 2;

			_spinVariability = new SpinButton();
			_spinVariability.Value = 1;
			_spinVariability.DrawLinesColor = Color.White;
			_spinVariability.Id = "_spinVariability";
			_spinVariability.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_spinVariability.GridPositionX = 1;
			_spinVariability.GridPositionY = 2;

			_textWaterLand = new TextBlock();
			_textWaterLand.Text = "Water/Land(60%):";
			_textWaterLand.TextColor = Color.White;
			_textWaterLand.DisabledTextColor = new Color
			{
				B = 170,
				G = 170,
				R = 170,
				A = 255,
			};
			_textWaterLand.Id = "_textWaterLand";
			_textWaterLand.GridPositionY = 3;

			_sliderWaterLand = new HorizontalSlider();
			_sliderWaterLand.Maximum = 100;
			_sliderWaterLand.Id = "_sliderWaterLand";
			_sliderWaterLand.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_sliderWaterLand.GridPositionX = 1;
			_sliderWaterLand.GridPositionY = 3;

			var grid1 = new Grid();
			grid1.DrawLinesColor = Color.White;
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Pixels,
				Value = 140,
			});
			grid1.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			grid1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			grid1.Widgets.Add(textBlock1);
			grid1.Widgets.Add(_spinWidth);
			grid1.Widgets.Add(textBlock2);
			grid1.Widgets.Add(_spinHeight);
			grid1.Widgets.Add(textBlock3);
			grid1.Widgets.Add(_spinVariability);
			grid1.Widgets.Add(_textWaterLand);
			grid1.Widgets.Add(_sliderWaterLand);

			_checkSurrondedByWater = new CheckBox();
			_checkSurrondedByWater.Text = "Surrounded By Water";
			_checkSurrondedByWater.TextColor = Color.White;
			_checkSurrondedByWater.ImageWidthHint = 10;
			_checkSurrondedByWater.ImageHeightHint = 10;
			_checkSurrondedByWater.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_checkSurrondedByWater.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_checkSurrondedByWater.Id = "_checkSurrondedByWater";
			_checkSurrondedByWater.GridPositionY = 1;

			_checkSmooth = new CheckBox();
			_checkSmooth.Text = "Smooth";
			_checkSmooth.TextColor = Color.White;
			_checkSmooth.ImageWidthHint = 10;
			_checkSmooth.ImageHeightHint = 10;
			_checkSmooth.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_checkSmooth.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_checkSmooth.Id = "_checkSmooth";
			_checkSmooth.GridPositionY = 2;

			_checkRemoveSmalIslands = new CheckBox();
			_checkRemoveSmalIslands.Text = "Remove Small Islands";
			_checkRemoveSmalIslands.TextColor = Color.White;
			_checkRemoveSmalIslands.ImageWidthHint = 10;
			_checkRemoveSmalIslands.ImageHeightHint = 10;
			_checkRemoveSmalIslands.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_checkRemoveSmalIslands.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_checkRemoveSmalIslands.Id = "_checkRemoveSmalIslands";
			_checkRemoveSmalIslands.GridPositionY = 3;

			_checkRemoveSmallLakes = new CheckBox();
			_checkRemoveSmallLakes.Text = "Remove Small Lakes";
			_checkRemoveSmallLakes.TextColor = Color.White;
			_checkRemoveSmallLakes.ImageWidthHint = 10;
			_checkRemoveSmallLakes.ImageHeightHint = 10;
			_checkRemoveSmallLakes.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_checkRemoveSmallLakes.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_checkRemoveSmallLakes.Id = "_checkRemoveSmallLakes";
			_checkRemoveSmallLakes.GridPositionY = 4;

			_buttonGenerate = new TextButton();
			_buttonGenerate.Text = "Generate";
			_buttonGenerate.TextColor = Color.White;
			_buttonGenerate.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_buttonGenerate.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_buttonGenerate.Id = "_buttonGenerate";
			_buttonGenerate.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_buttonGenerate.GridPositionY = 5;

			var textBlock4 = new TextBlock();
			textBlock4.Text = "View Mode:";
			textBlock4.TextColor = Color.White;
			textBlock4.DisabledTextColor = new Color
			{
				B = 170,
				G = 170,
				R = 170,
				A = 255,
			};

			var listItem1 = new ListItem();
			listItem1.Text = "Normal";

			var listItem2 = new ListItem();
			listItem2.Text = "Siluette";

			_comboViewMode = new ComboBox();
			_comboViewMode.SelectedIndex = 0;
			_comboViewMode.Id = "_comboViewMode";
			_comboViewMode.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_comboViewMode.GridPositionX = 1;
			_comboViewMode.Items.Add(listItem1);
			_comboViewMode.Items.Add(listItem2);

			var grid2 = new Grid();
			grid2.DrawLinesColor = Color.White;
			grid2.ColumnSpacing = 8;
			grid2.ColumnsProportions.Add(new Grid.Proportion());
			grid2.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid2.RowsProportions.Add(new Grid.Proportion());
			grid2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			grid2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			grid2.GridPositionY = 6;
			grid2.Widgets.Add(textBlock4);
			grid2.Widgets.Add(_comboViewMode);

			_buttonSaveAsPng = new TextButton();
			_buttonSaveAsPng.Text = "Save As PNG...";
			_buttonSaveAsPng.TextColor = Color.White;
			_buttonSaveAsPng.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_buttonSaveAsPng.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_buttonSaveAsPng.Id = "_buttonSaveAsPng";
			_buttonSaveAsPng.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_buttonSaveAsPng.GridPositionY = 7;

			var grid3 = new Grid();
			grid3.DrawLinesColor = Color.White;
			grid3.RowSpacing = 8;
			grid3.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid3.RowsProportions.Add(new Grid.Proportion());
			grid3.RowsProportions.Add(new Grid.Proportion());
			grid3.RowsProportions.Add(new Grid.Proportion());
			grid3.RowsProportions.Add(new Grid.Proportion());
			grid3.RowsProportions.Add(new Grid.Proportion());
			grid3.RowsProportions.Add(new Grid.Proportion());
			grid3.RowsProportions.Add(new Grid.Proportion());
			grid3.RowsProportions.Add(new Grid.Proportion());
			grid3.RowsProportions.Add(new Grid.Proportion());
			grid3.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			grid3.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			grid3.Widgets.Add(grid1);
			grid3.Widgets.Add(_checkSurrondedByWater);
			grid3.Widgets.Add(_checkSmooth);
			grid3.Widgets.Add(_checkRemoveSmalIslands);
			grid3.Widgets.Add(_checkRemoveSmallLakes);
			grid3.Widgets.Add(_buttonGenerate);
			grid3.Widgets.Add(grid2);
			grid3.Widgets.Add(_buttonSaveAsPng);

			_imageGenerated = new Image();
			_imageGenerated.Color = Color.White;
			_imageGenerated.Id = "_imageGenerated";

			_textGenerating = new TextBlock();
			_textGenerating.Text = "Generating...";
			_textGenerating.TextColor = Color.White;
			_textGenerating.DisabledTextColor = new Color
			{
				B = 170,
				G = 170,
				R = 170,
				A = 255,
			};
			_textGenerating.Id = "_textGenerating";
			_textGenerating.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_textGenerating.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;

			var panel1 = new Panel();
			panel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			panel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			panel1.GridPositionX = 2;
			panel1.Widgets.Add(_imageGenerated);
			panel1.Widgets.Add(_textGenerating);

			
			Id = "_splitPane";
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			Widgets.Add(grid3);
			Widgets.Add(panel1);
		}

		
		public SpinButton _spinWidth;
		public SpinButton _spinHeight;
		public SpinButton _spinVariability;
		public TextBlock _textWaterLand;
		public HorizontalSlider _sliderWaterLand;
		public CheckBox _checkSurrondedByWater;
		public CheckBox _checkSmooth;
		public CheckBox _checkRemoveSmalIslands;
		public CheckBox _checkRemoveSmallLakes;
		public TextButton _buttonGenerate;
		public ComboBox _comboViewMode;
		public TextButton _buttonSaveAsPng;
		public Image _imageGenerated;
		public TextBlock _textGenerating;
	}
}