/* Generated by Myra UI Editor at 1/2/2018 5:27:13 PM */

using System;
using System.Collections.Generic;
using Myra.Graphics2D.UI;
using Myra.Utility;

namespace Myra.Samples.TabControl
{
	public partial class TabControl: Grid
	{
		private readonly List<TextButton> _buttons = new List<TextButton>();

		public AllWidgets AllWidgets { get; private set; }
		public GridTabPage GridTabPage { get; private set; }
		public Notepad Notepad { get; private set; }

		public TabControl()
		{
			BuildUI();

			_buttons.Add(_buttonAllWidgets);
			_buttons.Add(_buttonGrid);
			_buttons.Add(_buttonNotepad);

			_buttonAllWidgets.MouseDown += ButtonAllWidgetsOnMouseDown;
			_buttonGrid.MouseDown += ButtonGridOnMouseDown;
			_buttonNotepad.MouseDown += ButtonNotepadOnMouseDown;

			// Initially 'AllWidgets' tab is selected
			_buttonAllWidgets.Press();
		}

		private void ButtonNotepadOnMouseDown(object sender, GenericEventArgs<MouseButtons> genericEventArgs)
		{
			if (Notepad == null)
			{
				Notepad = new Notepad();
			}

			_panelContent.Widgets.Clear();
			_panelContent.Widgets.Add(Notepad);

			SetIsPressed(_buttonNotepad);
		}

		private void ButtonGridOnMouseDown(object sender, GenericEventArgs<MouseButtons> genericEventArgs)
		{
			if (GridTabPage == null)
			{
				GridTabPage = new GridTabPage();
			}

			_panelContent.Widgets.Clear();
			_panelContent.Widgets.Add(GridTabPage);

			SetIsPressed(_buttonGrid);
		}

		private void ButtonAllWidgetsOnMouseDown(object sender, GenericEventArgs<MouseButtons> genericEventArgs)
		{
			if (AllWidgets == null)
			{
				AllWidgets = new AllWidgets();
			}

			_panelContent.Widgets.Clear();
			_panelContent.Widgets.Add(AllWidgets);

			SetIsPressed(_buttonAllWidgets);
		}

		private void SetIsPressed(TextButton exception)
		{
			exception.IsPressed = true;

			foreach (var b in _buttons)
			{
				if (b == exception)
				{
					continue;
				}

				b.IsPressed = false;
			}
		}
	}
}