/* Generated by Myra UI Editor at 10/22/2017 6:56:04 PM */
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;

namespace 	Myra.UIEditor.UI
{
	partial class OptionsWidget
	{
		private void BuildUI()
		{
			_checkBoxWidgetFrames = new CheckBox();
			_checkBoxWidgetFrames.Text = "Draw green frame around every widget";
			_checkBoxWidgetFrames.TextColor = Color.White;
			_checkBoxWidgetFrames.ImageWidthHint = 10;
			_checkBoxWidgetFrames.ImageHeightHint = 10;
			_checkBoxWidgetFrames.ImageVisible = true;
			_checkBoxWidgetFrames.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_checkBoxWidgetFrames.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_checkBoxWidgetFrames.Enabled = true;
			_checkBoxWidgetFrames.Id = "_checkBoxWidgetFrames";
			_checkBoxWidgetFrames.XHint = 0;
			_checkBoxWidgetFrames.YHint = 0;
			_checkBoxWidgetFrames.WidthHint = null;
			_checkBoxWidgetFrames.HeightHint = null;
			_checkBoxWidgetFrames.PaddingLeft = 0;
			_checkBoxWidgetFrames.PaddingRight = 0;
			_checkBoxWidgetFrames.PaddingTop = 0;
			_checkBoxWidgetFrames.PaddingBottom = 0;
			_checkBoxWidgetFrames.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			_checkBoxWidgetFrames.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			_checkBoxWidgetFrames.GridPositionX = 0;
			_checkBoxWidgetFrames.GridPositionY = 0;
			_checkBoxWidgetFrames.GridSpanX = 1;
			_checkBoxWidgetFrames.GridSpanY = 1;
			_checkBoxWidgetFrames.Visible = true;
			_checkBoxWidgetFrames.ClipToBounds = false;
			_checkBoxWidgetFrames.CanFocus = false;

			_checkBoxFocusedWidgetFrame = new CheckBox();
			_checkBoxFocusedWidgetFrame.Text = "Draw red frame around the focused widget";
			_checkBoxFocusedWidgetFrame.TextColor = Color.White;
			_checkBoxFocusedWidgetFrame.ImageWidthHint = 10;
			_checkBoxFocusedWidgetFrame.ImageHeightHint = 10;
			_checkBoxFocusedWidgetFrame.ImageVisible = true;
			_checkBoxFocusedWidgetFrame.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_checkBoxFocusedWidgetFrame.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_checkBoxFocusedWidgetFrame.Enabled = true;
			_checkBoxFocusedWidgetFrame.Id = "_checkBoxFocusedWidgetFrame";
			_checkBoxFocusedWidgetFrame.XHint = 0;
			_checkBoxFocusedWidgetFrame.YHint = 0;
			_checkBoxFocusedWidgetFrame.WidthHint = null;
			_checkBoxFocusedWidgetFrame.HeightHint = null;
			_checkBoxFocusedWidgetFrame.PaddingLeft = 0;
			_checkBoxFocusedWidgetFrame.PaddingRight = 0;
			_checkBoxFocusedWidgetFrame.PaddingTop = 0;
			_checkBoxFocusedWidgetFrame.PaddingBottom = 0;
			_checkBoxFocusedWidgetFrame.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			_checkBoxFocusedWidgetFrame.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			_checkBoxFocusedWidgetFrame.GridPositionX = 0;
			_checkBoxFocusedWidgetFrame.GridPositionY = 1;
			_checkBoxFocusedWidgetFrame.GridSpanX = 1;
			_checkBoxFocusedWidgetFrame.GridSpanY = 1;
			_checkBoxFocusedWidgetFrame.Visible = true;
			_checkBoxFocusedWidgetFrame.ClipToBounds = false;
			_checkBoxFocusedWidgetFrame.CanFocus = false;

			_checkBoxGlyphFrames = new CheckBox();
			_checkBoxGlyphFrames.Text = "Draw white frame around every letter glyph";
			_checkBoxGlyphFrames.TextColor = Color.White;
			_checkBoxGlyphFrames.ImageWidthHint = 10;
			_checkBoxGlyphFrames.ImageHeightHint = 10;
			_checkBoxGlyphFrames.ImageVisible = true;
			_checkBoxGlyphFrames.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_checkBoxGlyphFrames.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_checkBoxGlyphFrames.Enabled = true;
			_checkBoxGlyphFrames.Id = "_checkBoxGlyphFrames";
			_checkBoxGlyphFrames.XHint = 0;
			_checkBoxGlyphFrames.YHint = 0;
			_checkBoxGlyphFrames.WidthHint = null;
			_checkBoxGlyphFrames.HeightHint = null;
			_checkBoxGlyphFrames.PaddingLeft = 0;
			_checkBoxGlyphFrames.PaddingRight = 0;
			_checkBoxGlyphFrames.PaddingTop = 0;
			_checkBoxGlyphFrames.PaddingBottom = 0;
			_checkBoxGlyphFrames.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			_checkBoxGlyphFrames.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			_checkBoxGlyphFrames.GridPositionX = 0;
			_checkBoxGlyphFrames.GridPositionY = 2;
			_checkBoxGlyphFrames.GridSpanX = 1;
			_checkBoxGlyphFrames.GridSpanY = 1;
			_checkBoxGlyphFrames.Visible = true;
			_checkBoxGlyphFrames.ClipToBounds = false;
			_checkBoxGlyphFrames.CanFocus = false;

			_checkBoxShowDebugInfo = new CheckBox();
			_checkBoxShowDebugInfo.Text = "Show debugging info";
			_checkBoxShowDebugInfo.TextColor = Color.White;
			_checkBoxShowDebugInfo.ImageWidthHint = 10;
			_checkBoxShowDebugInfo.ImageHeightHint = 10;
			_checkBoxShowDebugInfo.ImageVisible = true;
			_checkBoxShowDebugInfo.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_checkBoxShowDebugInfo.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_checkBoxShowDebugInfo.Enabled = true;
			_checkBoxShowDebugInfo.Id = "_checkBoxShowDebugInfo";
			_checkBoxShowDebugInfo.XHint = 0;
			_checkBoxShowDebugInfo.YHint = 0;
			_checkBoxShowDebugInfo.WidthHint = null;
			_checkBoxShowDebugInfo.HeightHint = null;
			_checkBoxShowDebugInfo.PaddingLeft = 0;
			_checkBoxShowDebugInfo.PaddingRight = 0;
			_checkBoxShowDebugInfo.PaddingTop = 0;
			_checkBoxShowDebugInfo.PaddingBottom = 0;
			_checkBoxShowDebugInfo.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			_checkBoxShowDebugInfo.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			_checkBoxShowDebugInfo.GridPositionX = 0;
			_checkBoxShowDebugInfo.GridPositionY = 3;
			_checkBoxShowDebugInfo.GridSpanX = 1;
			_checkBoxShowDebugInfo.GridSpanY = 1;
			_checkBoxShowDebugInfo.Visible = true;
			_checkBoxShowDebugInfo.ClipToBounds = false;
			_checkBoxShowDebugInfo.CanFocus = false;

			_checkBoxDisableScissors = new CheckBox();
			_checkBoxDisableScissors.Text = "Disable scissors";
			_checkBoxDisableScissors.TextColor = Color.White;
			_checkBoxDisableScissors.ImageWidthHint = 10;
			_checkBoxDisableScissors.ImageHeightHint = 10;
			_checkBoxDisableScissors.ImageVisible = true;
			_checkBoxDisableScissors.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_checkBoxDisableScissors.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_checkBoxDisableScissors.Enabled = true;
			_checkBoxDisableScissors.Id = "_checkBoxDisableScissors";
			_checkBoxDisableScissors.XHint = 0;
			_checkBoxDisableScissors.YHint = 0;
			_checkBoxDisableScissors.WidthHint = null;
			_checkBoxDisableScissors.HeightHint = null;
			_checkBoxDisableScissors.PaddingLeft = 0;
			_checkBoxDisableScissors.PaddingRight = 0;
			_checkBoxDisableScissors.PaddingTop = 0;
			_checkBoxDisableScissors.PaddingBottom = 0;
			_checkBoxDisableScissors.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			_checkBoxDisableScissors.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			_checkBoxDisableScissors.GridPositionX = 0;
			_checkBoxDisableScissors.GridPositionY = 4;
			_checkBoxDisableScissors.GridSpanX = 1;
			_checkBoxDisableScissors.GridSpanY = 1;
			_checkBoxDisableScissors.Visible = true;
			_checkBoxDisableScissors.ClipToBounds = false;
			_checkBoxDisableScissors.CanFocus = false;

			
			DrawLines = false;
			DrawLinesColor = Color.White;
			ColumnSpacing = 0;
			RowSpacing = 0;
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Auto,
				Value = 1,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Auto,
				Value = 1,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Auto,
				Value = 1,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Auto,
				Value = 1,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Auto,
				Value = 1,
			});
			TotalRowsPart = null;
			TotalColumnsPart = null;
			Enabled = true;
			Id = "Root";
			XHint = 0;
			YHint = 0;
			WidthHint = null;
			HeightHint = null;
			PaddingLeft = 0;
			PaddingRight = 0;
			PaddingTop = 0;
			PaddingBottom = 0;
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			GridPositionX = 0;
			GridPositionY = 0;
			GridSpanX = 1;
			GridSpanY = 1;
			Visible = true;
			ClipToBounds = false;
			CanFocus = false;
			Widgets.Add(_checkBoxWidgetFrames);
			Widgets.Add(_checkBoxFocusedWidgetFrame);
			Widgets.Add(_checkBoxGlyphFrames);
			Widgets.Add(_checkBoxShowDebugInfo);
			Widgets.Add(_checkBoxDisableScissors);
		}

		
		public CheckBox _checkBoxWidgetFrames;
		public CheckBox _checkBoxFocusedWidgetFrame;
		public CheckBox _checkBoxGlyphFrames;
		public CheckBox _checkBoxShowDebugInfo;
		public CheckBox _checkBoxDisableScissors;
	}
}