/* Generated by Myra UI Editor at 10/22/2017 6:06:59 PM */
using Myra.Graphics2D.UI;

namespace 	Myra.UIEditor.UI
{
	public partial class OptionsWidget: Grid
	{
		public OptionsWidget()
		{
			BuildUI();
		}
	}
}