/* Generated by Myra UI Editor at 10/15/2017 3:52:43 PM */
using Myra.Graphics2D.UI;

namespace Myra.UIEditor.UI
{
	public partial class StudioWidget: Grid
	{
		public StudioWidget()
		{
			BuildUI();
		}
	}
}