/* Generated by Myra UI Editor at 10/15/2017 4:09:06 PM */
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;

namespace Myra.UIEditor.UI
{
	partial class StudioWidget
	{
		private void BuildUI()
		{
			_menuFileNew = new MenuItem();
			_menuFileNew.Id = "_menuFileNew";
			_menuFileNew.Text = "&New";
			_menuFileNew.Color = null;

			_menuFileOpen = new MenuItem();
			_menuFileOpen.Id = "_menuFileOpen";
			_menuFileOpen.Text = "&Open";
			_menuFileOpen.Color = null;

			_menuFileSave = new MenuItem();
			_menuFileSave.Id = "_menuFileSave";
			_menuFileSave.Text = "&Save";
			_menuFileSave.Color = null;

			_menuFileSaveAs = new MenuItem();
			_menuFileSaveAs.Id = "_menuFileSaveAs";
			_menuFileSaveAs.Text = "Save &As...";
			_menuFileSaveAs.Color = null;

			_menuFileExportToCS = new MenuItem();
			_menuFileExportToCS.Id = "_menuFileExportToCS";
			_menuFileExportToCS.Text = "&Export To C#...";
			_menuFileExportToCS.Color = null;

			var menuSeparator1 = new MenuSeparator();
			menuSeparator1.Id = null;

			_menuFileQuit = new MenuItem();
			_menuFileQuit.Id = "_menuFileQuit";
			_menuFileQuit.Text = "&Quit";
			_menuFileQuit.Color = null;

			var menuItem1 = new MenuItem();
			menuItem1.Id = "";
			menuItem1.Text = "&File";
			menuItem1.Color = null;
			menuItem1.Items.Add(_menuFileNew);
			menuItem1.Items.Add(_menuFileOpen);
			menuItem1.Items.Add(_menuFileSave);
			menuItem1.Items.Add(_menuFileSaveAs);
			menuItem1.Items.Add(_menuFileExportToCS);
			menuItem1.Items.Add(menuSeparator1);
			menuItem1.Items.Add(_menuFileQuit);

			_menuControlsAddButton = new MenuItem();
			_menuControlsAddButton.Id = "_menuControlsAddButton";
			_menuControlsAddButton.Text = "Add Button";
			_menuControlsAddButton.Color = null;

			_menuControlsAddCheckBox = new MenuItem();
			_menuControlsAddCheckBox.Id = "_menuControlsAddCheckBox";
			_menuControlsAddCheckBox.Text = "Add CheckBox";
			_menuControlsAddCheckBox.Color = null;

			_menuControlsAddImageButton = new MenuItem();
			_menuControlsAddImageButton.Id = "_menuControlsAddImageButton";
			_menuControlsAddImageButton.Text = "Add ImageButton";
			_menuControlsAddImageButton.Color = null;

			_menuControlsAddHorizontalSlider = new MenuItem();
			_menuControlsAddHorizontalSlider.Id = "_menuControlsAddHorizontalSlider";
			_menuControlsAddHorizontalSlider.Text = "Add HorizontalSlider";
			_menuControlsAddHorizontalSlider.Color = null;

			_menuControlsAddVerticalSlider = new MenuItem();
			_menuControlsAddVerticalSlider.Id = "_menuControlsAddVerticalSlider";
			_menuControlsAddVerticalSlider.Text = "Add VerticalSlider";
			_menuControlsAddVerticalSlider.Color = null;

			_menuControlsAddHorizontalProgressBar = new MenuItem();
			_menuControlsAddHorizontalProgressBar.Id = "_menuControlsAddHorizontalProgressBar";
			_menuControlsAddHorizontalProgressBar.Text = "Add Horizontal ProgressBar";
			_menuControlsAddHorizontalProgressBar.Color = null;

			_menuControlsAddVerticalProgressBar = new MenuItem();
			_menuControlsAddVerticalProgressBar.Id = "_menuControlsAddVerticalProgressBar";
			_menuControlsAddVerticalProgressBar.Text = "Add Vertical ProgressBar";
			_menuControlsAddVerticalProgressBar.Color = null;

			_menuControlsAddComboBox = new MenuItem();
			_menuControlsAddComboBox.Id = "_menuControlsAddComboBox";
			_menuControlsAddComboBox.Text = "Add ComboBox";
			_menuControlsAddComboBox.Color = null;

			_menuControlsAddListBox = new MenuItem();
			_menuControlsAddListBox.Id = "_menuControlsAddListBox";
			_menuControlsAddListBox.Text = "Add ListBox";
			_menuControlsAddListBox.Color = null;

			_menuControlsAddPanel = new MenuItem();
			_menuControlsAddPanel.Id = "_menuControlsAddPanel";
			_menuControlsAddPanel.Text = "Add Panel";
			_menuControlsAddPanel.Color = null;

			_menuControlsAddGrid = new MenuItem();
			_menuControlsAddGrid.Id = "_menuControlsAddGrid";
			_menuControlsAddGrid.Text = "Add Grid";
			_menuControlsAddGrid.Color = null;

			_menuControlsAddImage = new MenuItem();
			_menuControlsAddImage.Id = "_menuControlsAddImage";
			_menuControlsAddImage.Text = "Add Image";
			_menuControlsAddImage.Color = null;

			_menuControlsAddHorizontalMenu = new MenuItem();
			_menuControlsAddHorizontalMenu.Id = "_menuControlsAddHorizontalMenu";
			_menuControlsAddHorizontalMenu.Text = "Add HorizontalMenu";
			_menuControlsAddHorizontalMenu.Color = null;

			_menuControlsAddVerticalMenu = new MenuItem();
			_menuControlsAddVerticalMenu.Id = "_menuControlsAddVerticalMenu";
			_menuControlsAddVerticalMenu.Text = "Add Vertical Menu";
			_menuControlsAddVerticalMenu.Color = null;

			_menuControlsAddScrollPane = new MenuItem();
			_menuControlsAddScrollPane.Id = "_menuControlsAddScrollPane";
			_menuControlsAddScrollPane.Text = "Add ScrollPane";
			_menuControlsAddScrollPane.Color = null;

			_menuControlsAddHorizontalSplitPane = new MenuItem();
			_menuControlsAddHorizontalSplitPane.Id = "_menuControlsAddHorizontalSplitPane";
			_menuControlsAddHorizontalSplitPane.Text = "Add Horizontal SplitPane";
			_menuControlsAddHorizontalSplitPane.Color = null;

			_menuControlsAddVerticalSplitPane = new MenuItem();
			_menuControlsAddVerticalSplitPane.Id = "_menuControlsAddVerticalSplitPane";
			_menuControlsAddVerticalSplitPane.Text = "Add Vertical SplitPane";
			_menuControlsAddVerticalSplitPane.Color = null;

			_menuControlsAddTextBlock = new MenuItem();
			_menuControlsAddTextBlock.Id = "_menuControlsAddTextBlock";
			_menuControlsAddTextBlock.Text = "Add TextBlock";
			_menuControlsAddTextBlock.Color = null;

			_menuControlsAddTextField = new MenuItem();
			_menuControlsAddTextField.Id = "_menuControlsAddTextField";
			_menuControlsAddTextField.Text = "Add TextField";
			_menuControlsAddTextField.Color = null;

			_menuControlsAddSpinButton = new MenuItem();
			_menuControlsAddSpinButton.Id = "_menuControlsAddSpinButton";
			_menuControlsAddSpinButton.Text = "Add SpinButton";
			_menuControlsAddSpinButton.Color = null;

			var menuSeparator2 = new MenuSeparator();
			menuSeparator2.Id = null;

			_menuControlsAddMenuItem = new MenuItem();
			_menuControlsAddMenuItem.Id = "_menuControlsAddMenuItem";
			_menuControlsAddMenuItem.Text = "Add Menu Item";
			_menuControlsAddMenuItem.Color = null;

			_menuControlsAddMenuSeparator = new MenuItem();
			_menuControlsAddMenuSeparator.Id = "_menuControlsAddMenuSeparator";
			_menuControlsAddMenuSeparator.Text = "Add Menu Separator";
			_menuControlsAddMenuSeparator.Color = null;

			_menuControls = new MenuItem();
			_menuControls.Id = "_menuControls";
			_menuControls.Text = "&Controls";
			_menuControls.Color = null;
			_menuControls.Items.Add(_menuControlsAddButton);
			_menuControls.Items.Add(_menuControlsAddCheckBox);
			_menuControls.Items.Add(_menuControlsAddImageButton);
			_menuControls.Items.Add(_menuControlsAddHorizontalSlider);
			_menuControls.Items.Add(_menuControlsAddVerticalSlider);
			_menuControls.Items.Add(_menuControlsAddHorizontalProgressBar);
			_menuControls.Items.Add(_menuControlsAddVerticalProgressBar);
			_menuControls.Items.Add(_menuControlsAddComboBox);
			_menuControls.Items.Add(_menuControlsAddListBox);
			_menuControls.Items.Add(_menuControlsAddPanel);
			_menuControls.Items.Add(_menuControlsAddGrid);
			_menuControls.Items.Add(_menuControlsAddImage);
			_menuControls.Items.Add(_menuControlsAddHorizontalMenu);
			_menuControls.Items.Add(_menuControlsAddVerticalMenu);
			_menuControls.Items.Add(_menuControlsAddScrollPane);
			_menuControls.Items.Add(_menuControlsAddHorizontalSplitPane);
			_menuControls.Items.Add(_menuControlsAddVerticalSplitPane);
			_menuControls.Items.Add(_menuControlsAddTextBlock);
			_menuControls.Items.Add(_menuControlsAddTextField);
			_menuControls.Items.Add(_menuControlsAddSpinButton);
			_menuControls.Items.Add(menuSeparator2);
			_menuControls.Items.Add(_menuControlsAddMenuItem);
			_menuControls.Items.Add(_menuControlsAddMenuSeparator);

			_menuHelpAbout = new MenuItem();
			_menuHelpAbout.Id = "_menuHelpAbout";
			_menuHelpAbout.Text = "&About";
			_menuHelpAbout.Color = null;

			var menuItem2 = new MenuItem();
			menuItem2.Id = "";
			menuItem2.Text = "&Help";
			menuItem2.Color = null;
			menuItem2.Items.Add(_menuHelpAbout);

			var horizontalMenu1 = new HorizontalMenu();
			horizontalMenu1.DrawLines = false;
			horizontalMenu1.DrawLinesColor = Color.White;
			horizontalMenu1.Enabled = true;
			horizontalMenu1.Id = "";
			horizontalMenu1.XHint = 0;
			horizontalMenu1.YHint = 0;
			horizontalMenu1.WidthHint = null;
			horizontalMenu1.HeightHint = null;
			horizontalMenu1.PaddingLeft = 0;
			horizontalMenu1.PaddingRight = 0;
			horizontalMenu1.PaddingTop = 0;
			horizontalMenu1.PaddingBottom = 0;
			horizontalMenu1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			horizontalMenu1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			horizontalMenu1.GridPositionX = 0;
			horizontalMenu1.GridPositionY = 0;
			horizontalMenu1.GridSpanX = 1;
			horizontalMenu1.GridSpanY = 1;
			horizontalMenu1.Visible = true;
			horizontalMenu1.ClipToBounds = false;
			horizontalMenu1.Items.Add(menuItem1);
			horizontalMenu1.Items.Add(_menuControls);
			horizontalMenu1.Items.Add(menuItem2);

			_projectHolder = new Panel();
			_projectHolder.Enabled = true;
			_projectHolder.Id = "_projectHolder";
			_projectHolder.XHint = 0;
			_projectHolder.YHint = 0;
			_projectHolder.WidthHint = null;
			_projectHolder.HeightHint = null;
			_projectHolder.PaddingLeft = 0;
			_projectHolder.PaddingRight = 0;
			_projectHolder.PaddingTop = 0;
			_projectHolder.PaddingBottom = 0;
			_projectHolder.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_projectHolder.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_projectHolder.GridPositionX = 0;
			_projectHolder.GridPositionY = 0;
			_projectHolder.GridSpanX = 1;
			_projectHolder.GridSpanY = 1;
			_projectHolder.Visible = true;
			_projectHolder.ClipToBounds = false;
			_projectHolder.CanFocus = false;

			_explorerHolder = new Panel();
			_explorerHolder.Enabled = true;
			_explorerHolder.Id = "_explorerHolder";
			_explorerHolder.XHint = 0;
			_explorerHolder.YHint = 0;
			_explorerHolder.WidthHint = null;
			_explorerHolder.HeightHint = null;
			_explorerHolder.PaddingLeft = 0;
			_explorerHolder.PaddingRight = 0;
			_explorerHolder.PaddingTop = 0;
			_explorerHolder.PaddingBottom = 0;
			_explorerHolder.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_explorerHolder.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_explorerHolder.GridPositionX = 0;
			_explorerHolder.GridPositionY = 0;
			_explorerHolder.GridSpanX = 1;
			_explorerHolder.GridSpanY = 1;
			_explorerHolder.Visible = true;
			_explorerHolder.ClipToBounds = false;
			_explorerHolder.CanFocus = false;

			_propertyGridPane = new ScrollPane();
			_propertyGridPane.Child = null;
			_propertyGridPane.Enabled = true;
			_propertyGridPane.Id = "_propertyGridPane";
			_propertyGridPane.XHint = 0;
			_propertyGridPane.YHint = 0;
			_propertyGridPane.WidthHint = null;
			_propertyGridPane.HeightHint = null;
			_propertyGridPane.PaddingLeft = 0;
			_propertyGridPane.PaddingRight = 0;
			_propertyGridPane.PaddingTop = 0;
			_propertyGridPane.PaddingBottom = 0;
			_propertyGridPane.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_propertyGridPane.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_propertyGridPane.GridPositionX = 0;
			_propertyGridPane.GridPositionY = 2;
			_propertyGridPane.GridSpanX = 1;
			_propertyGridPane.GridSpanY = 1;
			_propertyGridPane.Visible = true;
			_propertyGridPane.ClipToBounds = true;
			_propertyGridPane.CanFocus = true;

			_rightSplitPane = new VerticalSplitPane();
			_rightSplitPane.Enabled = true;
			_rightSplitPane.Id = "_rightSplitPane";
			_rightSplitPane.XHint = 0;
			_rightSplitPane.YHint = 0;
			_rightSplitPane.WidthHint = null;
			_rightSplitPane.HeightHint = null;
			_rightSplitPane.PaddingLeft = 0;
			_rightSplitPane.PaddingRight = 0;
			_rightSplitPane.PaddingTop = 0;
			_rightSplitPane.PaddingBottom = 0;
			_rightSplitPane.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_rightSplitPane.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_rightSplitPane.GridPositionX = 2;
			_rightSplitPane.GridPositionY = 0;
			_rightSplitPane.GridSpanX = 1;
			_rightSplitPane.GridSpanY = 1;
			_rightSplitPane.Visible = true;
			_rightSplitPane.ClipToBounds = false;
			_rightSplitPane.CanFocus = false;
			_rightSplitPane.Widgets.Add(_explorerHolder);
			_rightSplitPane.Widgets.Add(_propertyGridPane);

			_topSplitPane = new HorizontalSplitPane();
			_topSplitPane.Enabled = true;
			_topSplitPane.Id = "_topSplitPane";
			_topSplitPane.XHint = 0;
			_topSplitPane.YHint = 0;
			_topSplitPane.WidthHint = null;
			_topSplitPane.HeightHint = null;
			_topSplitPane.PaddingLeft = 0;
			_topSplitPane.PaddingRight = 0;
			_topSplitPane.PaddingTop = 0;
			_topSplitPane.PaddingBottom = 0;
			_topSplitPane.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_topSplitPane.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_topSplitPane.GridPositionX = 0;
			_topSplitPane.GridPositionY = 1;
			_topSplitPane.GridSpanX = 1;
			_topSplitPane.GridSpanY = 1;
			_topSplitPane.Visible = true;
			_topSplitPane.ClipToBounds = false;
			_topSplitPane.CanFocus = false;
			_topSplitPane.Widgets.Add(_projectHolder);
			_topSplitPane.Widgets.Add(_rightSplitPane);

			
			DrawLines = false;
			DrawLinesColor = Color.White;
			ColumnSpacing = 0;
			RowSpacing = 0;
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Auto,
				Value = 1,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
				Value = 1,
			});
			TotalRowsPart = null;
			TotalColumnsPart = null;
			Enabled = true;
			Id = "Root";
			XHint = 0;
			YHint = 0;
			WidthHint = null;
			HeightHint = null;
			PaddingLeft = 0;
			PaddingRight = 0;
			PaddingTop = 0;
			PaddingBottom = 0;
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			GridPositionX = 0;
			GridPositionY = 0;
			GridSpanX = 1;
			GridSpanY = 1;
			Visible = true;
			ClipToBounds = false;
			CanFocus = false;
			Widgets.Add(horizontalMenu1);
			Widgets.Add(_topSplitPane);
		}

		
		public MenuItem _menuFileNew;
		public MenuItem _menuFileOpen;
		public MenuItem _menuFileSave;
		public MenuItem _menuFileSaveAs;
		public MenuItem _menuFileExportToCS;
		public MenuItem _menuFileQuit;
		public MenuItem _menuControlsAddButton;
		public MenuItem _menuControlsAddCheckBox;
		public MenuItem _menuControlsAddImageButton;
		public MenuItem _menuControlsAddHorizontalSlider;
		public MenuItem _menuControlsAddVerticalSlider;
		public MenuItem _menuControlsAddHorizontalProgressBar;
		public MenuItem _menuControlsAddVerticalProgressBar;
		public MenuItem _menuControlsAddComboBox;
		public MenuItem _menuControlsAddListBox;
		public MenuItem _menuControlsAddPanel;
		public MenuItem _menuControlsAddGrid;
		public MenuItem _menuControlsAddImage;
		public MenuItem _menuControlsAddHorizontalMenu;
		public MenuItem _menuControlsAddVerticalMenu;
		public MenuItem _menuControlsAddScrollPane;
		public MenuItem _menuControlsAddHorizontalSplitPane;
		public MenuItem _menuControlsAddVerticalSplitPane;
		public MenuItem _menuControlsAddTextBlock;
		public MenuItem _menuControlsAddTextField;
		public MenuItem _menuControlsAddSpinButton;
		public MenuItem _menuControlsAddMenuItem;
		public MenuItem _menuControlsAddMenuSeparator;
		public MenuItem _menuControls;
		public MenuItem _menuHelpAbout;
		public Panel _projectHolder;
		public Panel _explorerHolder;
		public ScrollPane _propertyGridPane;
		public VerticalSplitPane _rightSplitPane;
		public HorizontalSplitPane _topSplitPane;
	}
}