/* Generated by MyraPad at 10/26/2023 4:39:25 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Myra.Samples.NonModalWindows.UI
{
	partial class MainPanel: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Window 1";

			_button1 = new ToggleButton();
			_button1.Id = "_button1";
			_button1.Content = label1;

			var label2 = new Label();
			label2.Text = "Window 2";

			_button2 = new ToggleButton();
			_button2.Id = "_button2";
			_button2.Content = label2;

			var label3 = new Label();
			label3.Text = "Window 3";

			_button3 = new ToggleButton();
			_button3.Id = "_button3";
			_button3.Content = label3;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(_button1);
			horizontalStackPanel1.Widgets.Add(_button2);
			horizontalStackPanel1.Widgets.Add(_button3);

			_labelOverGui = new Label();
			_labelOverGui.Text = "Is mouse over GUI: true";
			_labelOverGui.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			_labelOverGui.Id = "_labelOverGui";

			
			Widgets.Add(horizontalStackPanel1);
			Widgets.Add(_labelOverGui);
		}

		
		public ToggleButton _button1;
		public ToggleButton _button2;
		public ToggleButton _button3;
		public Label _labelOverGui;
	}
}
