/* Generated by MyraPad at 11/29/2023 6:40:28 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Myra.Samples.NonModalWindows.UI
{
	partial class Window3: Window
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "ItemItemItem0";

			var label2 = new Label();
			label2.Text = "ItemItemItem1";

			var label3 = new Label();
			label3.Text = "ItemItemItem2";

			var label4 = new Label();
			label4.Text = "ItemItemItem3";

			var label5 = new Label();
			label5.Text = "ItemItemItem4";

			var label6 = new Label();
			label6.Text = "ItemItemItem5";

			var label7 = new Label();
			label7.Text = "ItemItemItem6";

			var label8 = new Label();
			label8.Text = "ItemItemItem7";

			var label9 = new Label();
			label9.Text = "ItemItemItem8";

			var label10 = new Label();
			label10.Text = "ItemItemItem9";

			var listView1 = new ListView();
			listView1.MaxHeight = 150;
			listView1.Widgets.Add(label1);
			listView1.Widgets.Add(label2);
			listView1.Widgets.Add(label3);
			listView1.Widgets.Add(label4);
			listView1.Widgets.Add(label5);
			listView1.Widgets.Add(label6);
			listView1.Widgets.Add(label7);
			listView1.Widgets.Add(label8);
			listView1.Widgets.Add(label9);
			listView1.Widgets.Add(label10);

			var panel1 = new Panel();
			panel1.Widgets.Add(listView1);

			
			Title = "Window 3";
			Left = 805;
			Top = 288;
			Content = panel1;
		}

		
	}
}
