/* Generated by MyraPad at 9/8/2022 6:36:42 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace Myra.Samples.NonModalWindows.UI
{
	partial class Window1: Window
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "You have 10 points left to distribute";

			var label2 = new Label();
			label2.Text = "Strength";

			var spinButton1 = new SpinButton();
			spinButton1.Value = 5;
			spinButton1.Width = 50;
			Grid.SetColumn(spinButton1, 1);

			var label3 = new Label();
			label3.Text = "Dexterity";
			Grid.SetRow(label3, 1);

			var spinButton2 = new SpinButton();
			spinButton2.Value = 5;
			spinButton2.Width = 50;
			Grid.SetColumn(spinButton2, 1);
			Grid.SetRow(spinButton2, 1);

			var label4 = new Label();
			label4.Text = "Constitution";
			Grid.SetRow(label4, 2);

			var spinButton3 = new SpinButton();
			spinButton3.Value = 5;
			spinButton3.Width = 50;
			Grid.SetColumn(spinButton3, 1);
			Grid.SetRow(spinButton3, 2);

			var label5 = new Label();
			label5.Text = "Intelligence";
			Grid.SetRow(label5, 3);

			var spinButton4 = new SpinButton();
			spinButton4.Value = 5;
			spinButton4.Width = 50;
			Grid.SetColumn(spinButton4, 1);
			Grid.SetRow(spinButton4, 3);

			var label6 = new Label();
			label6.Text = "Wisdom";
			Grid.SetRow(label6, 4);

			var spinButton5 = new SpinButton();
			spinButton5.Value = 5;
			spinButton5.Width = 50;
			Grid.SetColumn(spinButton5, 1);
			Grid.SetRow(spinButton5, 4);

			var label7 = new Label();
			label7.Text = "Charisma";
			Grid.SetRow(label7, 5);

			var spinButton6 = new SpinButton();
			spinButton6.Value = 5;
			spinButton6.Width = 50;
			Grid.SetColumn(spinButton6, 1);
			Grid.SetRow(spinButton6, 5);

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.DefaultColumnProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.Widgets.Add(label2);
			grid1.Widgets.Add(spinButton1);
			grid1.Widgets.Add(label3);
			grid1.Widgets.Add(spinButton2);
			grid1.Widgets.Add(label4);
			grid1.Widgets.Add(spinButton3);
			grid1.Widgets.Add(label5);
			grid1.Widgets.Add(spinButton4);
			grid1.Widgets.Add(label6);
			grid1.Widgets.Add(spinButton5);
			grid1.Widgets.Add(label7);
			grid1.Widgets.Add(spinButton6);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(label1);
			verticalStackPanel1.Widgets.Add(grid1);

			
			Title = "Window 1";
			Left = 395;
			Top = 210;
			Content = verticalStackPanel1;
		}

		
	}
}
