/* Generated by MyraPad at 27.02.2020 21:09:17 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace Myra.Samples.NonModalWindows.UI
{
	partial class Window1: Window
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "You have 10 points left to distribute";

			var label2 = new Label();
			label2.Text = "Strength";

			var spinButton1 = new SpinButton();
			spinButton1.Value = 5;
			spinButton1.Width = 50;
			spinButton1.GridColumn = 1;

			var label3 = new Label();
			label3.Text = "Dexterity";
			label3.GridRow = 1;

			var spinButton2 = new SpinButton();
			spinButton2.Value = 5;
			spinButton2.Width = 50;
			spinButton2.GridColumn = 1;
			spinButton2.GridRow = 1;

			var label4 = new Label();
			label4.Text = "Constitution";
			label4.GridRow = 2;

			var spinButton3 = new SpinButton();
			spinButton3.Value = 5;
			spinButton3.Width = 50;
			spinButton3.GridColumn = 1;
			spinButton3.GridRow = 2;

			var label5 = new Label();
			label5.Text = "Intelligence";
			label5.GridRow = 3;

			var spinButton4 = new SpinButton();
			spinButton4.Value = 5;
			spinButton4.Width = 50;
			spinButton4.GridColumn = 1;
			spinButton4.GridRow = 3;

			var label6 = new Label();
			label6.Text = "Wisdom";
			label6.GridRow = 4;

			var spinButton5 = new SpinButton();
			spinButton5.Value = 5;
			spinButton5.Width = 50;
			spinButton5.GridColumn = 1;
			spinButton5.GridRow = 4;

			var label7 = new Label();
			label7.Text = "Charisma";
			label7.GridRow = 5;

			var spinButton6 = new SpinButton();
			spinButton6.Value = 5;
			spinButton6.Width = 50;
			spinButton6.GridColumn = 1;
			spinButton6.GridRow = 5;

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.DefaultColumnProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.Widgets.Add(label2);
			grid1.Widgets.Add(spinButton1);
			grid1.Widgets.Add(label3);
			grid1.Widgets.Add(spinButton2);
			grid1.Widgets.Add(label4);
			grid1.Widgets.Add(spinButton3);
			grid1.Widgets.Add(label5);
			grid1.Widgets.Add(spinButton4);
			grid1.Widgets.Add(label6);
			grid1.Widgets.Add(spinButton5);
			grid1.Widgets.Add(label7);
			grid1.Widgets.Add(spinButton6);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(label1);
			verticalStackPanel1.Widgets.Add(grid1);

			
			Title = "Window 1";
			Left = 353;
			Top = 97;
			Content = verticalStackPanel1;
		}

		
	}
}