/* Generated by MyraPad at 9/8/2022 6:36:48 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace Myra.Samples.NonModalWindows.UI
{
	partial class Window2: Window
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = @"Lorem ipsum /c[green]dolor sit amet, /c[red]consectetur adipisicing elit, sed do eiusmod /c[#AAAAAA]tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. /c{white}Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum!";
			label1.Wrap = true;

			var scrollViewer1 = new ScrollViewer();
			scrollViewer1.Content = label1;

			
			Title = "Window 2";
			Left = 436;
			Top = 231;
			Width = 200;
			Height = 200;
			Content = scrollViewer1;
		}

		
	}
}
