/* Generated by MyraPad at 9/8/2022 6:36:55 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace Myra.Samples.NonModalWindows.UI
{
	partial class Window3: Window
	{
		private void BuildUI()
		{
			var listItem1 = new ListItem();
			listItem1.Text = "ItemItemItem0";

			var listItem2 = new ListItem();
			listItem2.Text = "ItemItemItem1";

			var listItem3 = new ListItem();
			listItem3.Text = "ItemItemItem2";

			var listItem4 = new ListItem();
			listItem4.Text = "ItemItemItem3";

			var listItem5 = new ListItem();
			listItem5.Text = "ItemItemItem4";

			var listItem6 = new ListItem();
			listItem6.Text = "ItemItemItem5";

			var listItem7 = new ListItem();
			listItem7.Text = "ItemItemItem6";

			var listItem8 = new ListItem();
			listItem8.Text = "ItemItemItem7";

			var listItem9 = new ListItem();
			listItem9.Text = "ItemItemItem8";

			var listItem10 = new ListItem();
			listItem10.Text = "ItemItemItem9";

			var listBox1 = new ListBox();
			listBox1.MaxHeight = 150;
			listBox1.Items.Add(listItem1);
			listBox1.Items.Add(listItem2);
			listBox1.Items.Add(listItem3);
			listBox1.Items.Add(listItem4);
			listBox1.Items.Add(listItem5);
			listBox1.Items.Add(listItem6);
			listBox1.Items.Add(listItem7);
			listBox1.Items.Add(listItem8);
			listBox1.Items.Add(listItem9);
			listBox1.Items.Add(listItem10);

			var panel1 = new Panel();
			panel1.Widgets.Add(listBox1);

			
			Title = "Window 3";
			Left = 466;
			Top = 241;
			Content = panel1;
		}

		
	}
}
