/* Generated by Myra UI Editor at 11/16/2017 2:38:36 AM */

using Myra.Graphics2D.UI;
using Myra.Graphics2D.UI.ColorPicker;
using Myra.Graphics2D.UI.Styles;

namespace Myra.Samples.CustomUIStylesheet
{
	public partial class AllWidgets: HorizontalSplitPane
	{
		public AllWidgets()
		{
			BuildUI();

			_imageButton.Click += (sender, args) =>
			{
				var debugWindow = new DebugOptionsWindow();
				debugWindow.ShowModal(Desktop);
			};

			var tree = new TreeView();
			Grid.SetColumn(tree, 1);
			Grid.SetRow(tree, 8);

			var node1 = tree.AddSubNode(new Label
			{
				Text = "node1"
			});
			var node2 = node1.AddSubNode(new Label
			{
				Text = "node2"
			});

			var node4 = node2.AddSubNode(new Label
			{
				Text = "node6"
			});
			node4.AddSubNode(new Label
			{
				Text = "node11"
			});
			node4.AddSubNode(new Label
			{
				Text = "node12"
			});
			node4.AddSubNode(new Label
			{
				Text = "node13"
			});
			node4.AddSubNode(new Label
			{
				Text = "node14"
			});
			node4.AddSubNode(new Label
			{
				Text = "node15"
			});
			node4.AddSubNode(new Label
			{
				Text = "node16"
			});
			node4.AddSubNode(new Label
			{
				Text = "node17"
			});
			node4.AddSubNode(new Label
			{
				Text = "node18"
			});

			var node3 = node2.AddSubNode(new CheckButton
			{
				Content = new Label
				{
					Text = "CheckButton node"
				}
			});
			node3.AddSubNode(new Label
			{
				Text = "node4"
			});
			node3.AddSubNode(new CheckButton
			{
				Content = new Label { Text = "CheckButton node2" },
				CheckPosition = CheckPosition.Right,
				CheckContentSpacing = 8
			});

			var imageButtonContent = new HorizontalStackPanel
			{
				Spacing = 4
			};

			imageButtonContent.Widgets.Add(new Image
			{
				Renderable = Stylesheet.Current.Atlas["plus"]
			});

			imageButtonContent.Widgets.Add(new Label
			{
				Text = "Button node"
			});
			node3.AddSubNode(new Button
			{
				Content = imageButtonContent
			});
			node3.AddSubNode(new HorizontalSlider());

			var imageButtonContent2 = new HorizontalStackPanel
			{
				Spacing = 4
			};

			imageButtonContent2.Widgets.Add(new Label
			{
				Text = "ToggleButton node"
			});
			imageButtonContent2.Widgets.Add(new Image
			{
				Renderable = Stylesheet.Current.Atlas["minus"]
			});

			node3.AddSubNode(new ToggleButton
			{
				Content = imageButtonContent2
			});

			_gridRight.Widgets.Add(tree);
		}
	}
}