/* Generated by MyraPad at 10/23/2023 7:08:51 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Myra.Samples.CustomUIStylesheet
{
	partial class AllWidgets: HorizontalSplitPane
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Button:";

			_button = new ImageTextButton();
			_button.Text = "Button";
			_button.Id = "_button";
			Grid.SetColumn(_button, 1);

			_textButtonLabel = new Label();
			_textButtonLabel.Text = "Text Button:";
			_textButtonLabel.Id = "_textButtonLabel";
			Grid.SetRow(_textButtonLabel, 1);

			_textButton = new TextButton();
			_textButton.Text = "Button 2";
			_textButton.Id = "_textButton";
			Grid.SetColumn(_textButton, 1);
			Grid.SetRow(_textButton, 1);

			var label2 = new Label();
			label2.Text = "Image Button:";
			Grid.SetRow(label2, 2);

			_imageButton = new ImageButton();
			_imageButton.Id = "_imageButton";
			Grid.SetColumn(_imageButton, 1);
			Grid.SetRow(_imageButton, 2);

			var checkBox1 = new CheckBox();
			checkBox1.Text = "This is checkbox";
			checkBox1.ImageWidth = 10;
			checkBox1.ImageHeight = 10;
			Grid.SetRow(checkBox1, 3);
			Grid.SetColumnSpan(checkBox1, 2);

			var label3 = new Label();
			label3.Text = "Horizontal Slider:";
			Grid.SetRow(label3, 4);

			var horizontalSlider1 = new HorizontalSlider();
			Grid.SetColumn(horizontalSlider1, 1);
			Grid.SetRow(horizontalSlider1, 4);

			var label4 = new Label();
			label4.Text = "Combo Box:";
			Grid.SetRow(label4, 5);

			var listItem1 = new ListItem();
			listItem1.Text = "Red";
			listItem1.Color = Color.Red;

			var listItem2 = new ListItem();
			listItem2.Text = "Green";
			listItem2.Color = Color.Lime;

			var listItem3 = new ListItem();
			listItem3.Text = "Blue";
			listItem3.Color = ColorStorage.CreateColor(0, 128, 255, 255);

			var comboBox1 = new ComboBox();
			comboBox1.Width = 200;
			Grid.SetColumn(comboBox1, 1);
			Grid.SetRow(comboBox1, 5);
			comboBox1.Items.Add(listItem1);
			comboBox1.Items.Add(listItem2);
			comboBox1.Items.Add(listItem3);

			var label5 = new Label();
			label5.Text = "Text Field:";
			Grid.SetRow(label5, 6);

			var textBox1 = new TextBox();
			Grid.SetColumn(textBox1, 1);
			Grid.SetRow(textBox1, 6);

			var label6 = new Label();
			label6.Text = "List Box:";
			Grid.SetRow(label6, 7);

			var listItem4 = new ListItem();
			listItem4.Text = "Red";
			listItem4.Color = Color.Red;

			var listItem5 = new ListItem();
			listItem5.Text = "Green";
			listItem5.Color = Color.Lime;

			var listItem6 = new ListItem();
			listItem6.Text = "Blue";
			listItem6.Color = Color.Blue;

			var listBox1 = new ListBox();
			listBox1.Width = 200;
			Grid.SetColumn(listBox1, 1);
			Grid.SetRow(listBox1, 7);
			listBox1.Items.Add(listItem4);
			listBox1.Items.Add(listItem5);
			listBox1.Items.Add(listItem6);

			var label7 = new Label();
			label7.Text = "Tree";
			Grid.SetRow(label7, 8);

			_gridRight = new Grid();
			_gridRight.ColumnSpacing = 8;
			_gridRight.RowSpacing = 8;
			_gridRight.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			_gridRight.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			_gridRight.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			_gridRight.Id = "_gridRight";
			_gridRight.Widgets.Add(label1);
			_gridRight.Widgets.Add(_button);
			_gridRight.Widgets.Add(_textButtonLabel);
			_gridRight.Widgets.Add(_textButton);
			_gridRight.Widgets.Add(label2);
			_gridRight.Widgets.Add(_imageButton);
			_gridRight.Widgets.Add(checkBox1);
			_gridRight.Widgets.Add(label3);
			_gridRight.Widgets.Add(horizontalSlider1);
			_gridRight.Widgets.Add(label4);
			_gridRight.Widgets.Add(comboBox1);
			_gridRight.Widgets.Add(label5);
			_gridRight.Widgets.Add(textBox1);
			_gridRight.Widgets.Add(label6);
			_gridRight.Widgets.Add(listBox1);
			_gridRight.Widgets.Add(label7);

			var scrollViewer1 = new ScrollViewer();
			scrollViewer1.Content = _gridRight;

			var label8 = new Label();
			label8.Text = "Vertical Slider:";

			var verticalSlider1 = new VerticalSlider();
			verticalSlider1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Grid.SetRow(verticalSlider1, 1);

			var grid1 = new Grid();
			grid1.RowSpacing = 8;
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid1.Widgets.Add(label8);
			grid1.Widgets.Add(verticalSlider1);

			var label9 = new Label();
			label9.Text = "Progress Bars:";

			_horizontalProgressBar = new HorizontalProgressBar();
			_horizontalProgressBar.Id = "_horizontalProgressBar";
			Grid.SetRow(_horizontalProgressBar, 1);

			_verticalProgressBar = new VerticalProgressBar();
			_verticalProgressBar.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_verticalProgressBar.Id = "_verticalProgressBar";
			Grid.SetRow(_verticalProgressBar, 2);

			var grid2 = new Grid();
			grid2.RowSpacing = 8;
			grid2.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid2.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid2.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid2.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid2.Widgets.Add(label9);
			grid2.Widgets.Add(_horizontalProgressBar);
			grid2.Widgets.Add(_verticalProgressBar);

			var verticalSplitPane1 = new VerticalSplitPane();
			verticalSplitPane1.Widgets.Add(grid1);
			verticalSplitPane1.Widgets.Add(grid2);

			
			Widgets.Add(scrollViewer1);
			Widgets.Add(verticalSplitPane1);
		}

		
		public ImageTextButton _button;
		public Label _textButtonLabel;
		public TextButton _textButton;
		public ImageButton _imageButton;
		public Grid _gridRight;
		public HorizontalProgressBar _horizontalProgressBar;
		public VerticalProgressBar _verticalProgressBar;
	}
}
