/* Generated by MyraPad at 01.01.2020 17:49:35 */
using Myra.Assets;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace Myra.Samples.AssetManagement.UI
{
	partial class MainForm: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "My Game";
			label1.Font = AssetManager.Default.Load<SpriteFont>("fonts/arial64.fnt");
			label1.TextColor = Color.LightBlue;
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var menuItem1 = new MenuItem();
			menuItem1.Id = "";
			menuItem1.Text = "Start New Game";

			var menuItem2 = new MenuItem();
			menuItem2.Id = "";
			menuItem2.Text = "Options";

			var menuItem3 = new MenuItem();
			menuItem3.Id = "";
			menuItem3.Text = "Quit";

			var verticalMenu1 = new VerticalMenu();
			verticalMenu1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			verticalMenu1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			verticalMenu1.LabelFont = AssetManager.Default.Load<SpriteFont>("fonts/comicSans48.fnt");
			verticalMenu1.LabelColor = Color.Indigo;
			verticalMenu1.SelectionHoverBackground = AssetManager.Default.Load<IBrush>("#808000FF");
			verticalMenu1.SelectionBackground = AssetManager.Default.Load<IBrush>("#FFA500FF");
			verticalMenu1.Background = AssetManager.Default.Load<IBrush>("#00000000");
			verticalMenu1.Items.Add(menuItem1);
			verticalMenu1.Items.Add(menuItem2);
			verticalMenu1.Items.Add(menuItem3);

			var image1 = new Image();
			image1.Renderable = AssetManager.Default.Load<TextureRegion>("images/LogoOnly_64px.png");
			image1.Left = 10;
			image1.Top = -10;
			image1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

			var label2 = new Label();
			label2.Text = "Version 0.6";
			label2.Font = AssetManager.Default.Load<SpriteFont>("fonts/calibri32.fnt");
			label2.Left = -10;
			label2.Top = -10;
			label2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			label2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

			
			Background = AssetManager.Default.Load<IBrush>("#C78100FF");
			Widgets.Add(label1);
			Widgets.Add(verticalMenu1);
			Widgets.Add(image1);
			Widgets.Add(label2);
		}

		
	}
}