/* Generated by MyraPad at 01.01.2020 18:46:55 */
using Myra.Assets;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace Myra.Samples.AssetManagement.UI
{
	partial class MainForm: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "My Game";
			label1.Font = AssetManager.Default.Load<SpriteFont>("fonts/arial64.fnt");
			label1.TextColor = Color.LightBlue;
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			_menuItemStartNewGame = new MenuItem();
			_menuItemStartNewGame.Id = "_menuItemStartNewGame";
			_menuItemStartNewGame.Text = "Start New Game";

			_menuItemOptions = new MenuItem();
			_menuItemOptions.Id = "_menuItemOptions";
			_menuItemOptions.Text = "Options";

			_menuItemQuit = new MenuItem();
			_menuItemQuit.Id = "_menuItemQuit";
			_menuItemQuit.Text = "Quit";

			_mainMenu = new VerticalMenu();
			_mainMenu.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_mainMenu.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_mainMenu.LabelFont = AssetManager.Default.Load<SpriteFont>("fonts/comicSans48.fnt");
			_mainMenu.LabelColor = Color.Indigo;
			_mainMenu.SelectionHoverBackground = AssetManager.Default.Load<IBrush>("#808000FF");
			_mainMenu.SelectionBackground = AssetManager.Default.Load<IBrush>("#FFA500FF");
			_mainMenu.LabelHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_mainMenu.HoverIndexCanBeNull = false;
			_mainMenu.Id = "_mainMenu";
			_mainMenu.Background = AssetManager.Default.Load<IBrush>("#00000000");
			_mainMenu.Items.Add(_menuItemStartNewGame);
			_mainMenu.Items.Add(_menuItemOptions);
			_mainMenu.Items.Add(_menuItemQuit);

			var image1 = new Image();
			image1.Renderable = AssetManager.Default.Load<TextureRegion>("images/LogoOnly_64px.png");
			image1.Left = 10;
			image1.Top = -10;
			image1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

			var label2 = new Label();
			label2.Text = "Version 0.6";
			label2.Font = AssetManager.Default.Load<SpriteFont>("fonts/calibri32.fnt");
			label2.Left = -10;
			label2.Top = -10;
			label2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			label2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

			
			Background = AssetManager.Default.Load<IBrush>("#C78100FF");
			Widgets.Add(label1);
			Widgets.Add(_mainMenu);
			Widgets.Add(image1);
			Widgets.Add(label2);
		}

		
		public MenuItem _menuItemStartNewGame;
		public MenuItem _menuItemOptions;
		public MenuItem _menuItemQuit;
		public VerticalMenu _mainMenu;
	}
}