/* Generated by MyraPad at 3/15/2026 9:24:40 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace MyraPad.UI
{
	partial class AddNewWidgetDialog: Dialog
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Filter:";

			_textFilter = new TextBox();
			_textFilter.Id = "_textFilter";
			StackPanel.SetProportionType(_textFilter, Myra.Graphics2D.UI.ProportionType.Fill);

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(label1);
			horizontalStackPanel1.Widgets.Add(_textFilter);

			var label2 = new Label();
			label2.Text = "Button";

			var label3 = new Label();
			label3.Text = "Grid";

			_listWidgets = new ListView();
			_listWidgets.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_listWidgets.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_listWidgets.Id = "_listWidgets";
			StackPanel.SetProportionType(_listWidgets, Myra.Graphics2D.UI.ProportionType.Fill);
			_listWidgets.Widgets.Add(label2);
			_listWidgets.Widgets.Add(label3);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(_listWidgets);

			
			Title = "Add New Widget";
			Left = 564;
			Top = 28;
			Width = 400;
			Height = 600;
			Content = verticalStackPanel1;
		}

		
		public TextBox _textFilter;
		public ListView _listWidgets;
	}
}
