/* Generated by MyraPad at 25.09.2019 23:42:34 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace MyraPad.UI
{
	partial class ExportOptionsDialog: Dialog
	{
		private void BuildUI()
		{
			var textBlock1 = new Label();
			textBlock1.Text = "Class Name:";
			textBlock1.Id = "";
			textBlock1.GridRow = 1;

			_textClassName = new TextBox();
			_textClassName.Text = "";
			_textClassName.Id = "_textClassName";
			_textClassName.GridColumn = 1;
			_textClassName.GridRow = 1;

			var textBlock2 = new Label();
			textBlock2.Text = "Output Path:";
			textBlock2.GridRow = 2;

			_textOutputPath = new TextBox();
			_textOutputPath.Text = "";
			_textOutputPath.Id = "_textOutputPath";
			_textOutputPath.GridColumn = 1;
			_textOutputPath.GridRow = 2;

			_buttonChangeOutputPath = new TextButton();
			_buttonChangeOutputPath.Text = "Change...";
			_buttonChangeOutputPath.Id = "_buttonChangeOutputPath";
			_buttonChangeOutputPath.GridColumn = 2;
			_buttonChangeOutputPath.GridRow = 2;

			var textBlock3 = new Label();
			textBlock3.Text = "Namespace:";

			_textNamespace = new TextBox();
			_textNamespace.Text = "";
			_textNamespace.Id = "_textNamespace";
			_textNamespace.GridColumn = 1;

			Root = new Grid();
			Root.ColumnSpacing = 8;
			Root.RowSpacing = 8;
			Root.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			Root.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Root.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			Root.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Root.Id = "Root";
			Root.Width = 800;
			Root.Widgets.Add(textBlock1);
			Root.Widgets.Add(_textClassName);
			Root.Widgets.Add(textBlock2);
			Root.Widgets.Add(_textOutputPath);
			Root.Widgets.Add(_buttonChangeOutputPath);
			Root.Widgets.Add(textBlock3);
			Root.Widgets.Add(_textNamespace);

			
			Title = "Export";
			Left = 124;
			Top = 136;
			Content = Root;
		}

		
		public TextBox _textClassName;
		public TextBox _textOutputPath;
		public TextButton _buttonChangeOutputPath;
		public TextBox _textNamespace;
		public Grid Root;
	}
}