/* Generated by MyraPad at 3/14/2026 4:40:29 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace MyraPad.UI
{
	partial class ExportLightWindow: Window
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Copy To Clipboard";

			_buttonCopyToClipboard = new Button();
			_buttonCopyToClipboard.Id = "_buttonCopyToClipboard";
			_buttonCopyToClipboard.Content = label1;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Widgets.Add(_buttonCopyToClipboard);

			_textCode = new TextBox();
			_textCode.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_textCode.Id = "_textCode";

			var scrollViewer1 = new ScrollViewer();
			StackPanel.SetProportionType(scrollViewer1, Myra.Graphics2D.UI.ProportionType.Fill);
			scrollViewer1.Content = _textCode;

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(scrollViewer1);

			
			Title = "Export To C# Light";
			Left = 364;
			Top = 28;
			Width = 800;
			Height = 600;
			Content = verticalStackPanel1;
		}

		
		public Button _buttonCopyToClipboard;
		public TextBox _textCode;
	}
}
