/* Generated by MyraPad at 6/3/2026 11:38:11 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace MyraPad.UI
{
	partial class ImageEditorDialog: Dialog
	{
		private void BuildUI()
		{
			_textValue = new TextBox();
			_textValue.Readonly = true;
			_textValue.Width = 400;
			_textValue.Id = "_textValue";

			_panelColor = new Panel();
			_panelColor.Width = 32;
			_panelColor.Height = 32;
			_panelColor.Margin = new Thickness(4);
			_panelColor.Background = new SolidBrush("#FFCC01FF");
			_panelColor.Id = "_panelColor";

			var label1 = new Label();
			label1.Text = "Change...";

			_buttonChangeColor = new Button();
			_buttonChangeColor.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_buttonChangeColor.Id = "_buttonChangeColor";
			_buttonChangeColor.Content = label1;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			horizontalStackPanel1.Widgets.Add(_panelColor);
			horizontalStackPanel1.Widgets.Add(_buttonChangeColor);

			var label2 = new Label();
			label2.Text = "Set Image From Stylesheet";

			_buttomSetFromStylesheet = new Button();
			_buttomSetFromStylesheet.Id = "_buttomSetFromStylesheet";
			_buttomSetFromStylesheet.Content = label2;

			var label3 = new Label();
			label3.Text = "Set Image From External File";

			_buttonSetFromFile = new Button();
			_buttonSetFromFile.Id = "_buttonSetFromFile";
			_buttonSetFromFile.Content = label3;

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(_textValue);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(_buttomSetFromStylesheet);
			verticalStackPanel1.Widgets.Add(_buttonSetFromFile);

			
			Title = "Image Editor";
			Left = 458;
			Top = 358;
			Content = verticalStackPanel1;
		}

		
		public TextBox _textValue;
		public Panel _panelColor;
		public Button _buttonChangeColor;
		public Button _buttomSetFromStylesheet;
		public Button _buttonSetFromFile;
	}
}
