/* Generated by MyraPad at 27.02.2020 21:06:35 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace MyraPad.UI
{
	partial class NewProjectWizard: Dialog
	{
		private void BuildUI()
		{
			_radioButtonGrid = new RadioButton();
			_radioButtonGrid.Text = "Grid";
			_radioButtonGrid.Id = "_radioButtonGrid";

			_radioButtonHorizontalStackPanel = new RadioButton();
			_radioButtonHorizontalStackPanel.Text = "HorizontalStackPanel";
			_radioButtonHorizontalStackPanel.Id = "_radioButtonHorizontalStackPanel";

			_radioButtonVerticalStackPanel = new RadioButton();
			_radioButtonVerticalStackPanel.Text = "VerticalStackPanel";
			_radioButtonVerticalStackPanel.Id = "_radioButtonVerticalStackPanel";

			_radioButtonPanel = new RadioButton();
			_radioButtonPanel.Text = "Panel";
			_radioButtonPanel.Id = "_radioButtonPanel";

			_radioButtonScrollViewer = new RadioButton();
			_radioButtonScrollViewer.Text = "ScrollViewer";
			_radioButtonScrollViewer.Id = "_radioButtonScrollViewer";

			_radioButtonHorizontalSplitPane = new RadioButton();
			_radioButtonHorizontalSplitPane.Text = "HorizontalSplitPane";
			_radioButtonHorizontalSplitPane.Id = "_radioButtonHorizontalSplitPane";

			_radioButtonVerticalSplitPane = new RadioButton();
			_radioButtonVerticalSplitPane.Text = "VerticalSplitPane";
			_radioButtonVerticalSplitPane.Id = "_radioButtonVerticalSplitPane";

			_radioButtonWindow = new RadioButton();
			_radioButtonWindow.Text = "Window";
			_radioButtonWindow.Id = "_radioButtonWindow";

			_radioButtonDialog = new RadioButton();
			_radioButtonDialog.Text = "Dialog";
			_radioButtonDialog.Id = "_radioButtonDialog";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Widgets.Add(_radioButtonGrid);
			verticalStackPanel1.Widgets.Add(_radioButtonHorizontalStackPanel);
			verticalStackPanel1.Widgets.Add(_radioButtonVerticalStackPanel);
			verticalStackPanel1.Widgets.Add(_radioButtonPanel);
			verticalStackPanel1.Widgets.Add(_radioButtonScrollViewer);
			verticalStackPanel1.Widgets.Add(_radioButtonHorizontalSplitPane);
			verticalStackPanel1.Widgets.Add(_radioButtonVerticalSplitPane);
			verticalStackPanel1.Widgets.Add(_radioButtonWindow);
			verticalStackPanel1.Widgets.Add(_radioButtonDialog);

			
			Title = "Choose Root Container";
			Left = 383;
			Top = 95;
			Content = verticalStackPanel1;
		}

		
		public RadioButton _radioButtonGrid;
		public RadioButton _radioButtonHorizontalStackPanel;
		public RadioButton _radioButtonVerticalStackPanel;
		public RadioButton _radioButtonPanel;
		public RadioButton _radioButtonScrollViewer;
		public RadioButton _radioButtonHorizontalSplitPane;
		public RadioButton _radioButtonVerticalSplitPane;
		public RadioButton _radioButtonWindow;
		public RadioButton _radioButtonDialog;
	}
}