/* Generated by MyraPad at 24.09.2019 21:29:54 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace MyraPad.UI
{
	partial class NewProjectWizard: Dialog
	{
		private void BuildUI()
		{
			_radioButtonGrid = new RadioButton();
			_radioButtonGrid.Text = "Grid";
			_radioButtonGrid.Id = "_radioButtonGrid";

			_radioButtonHorizontalBox = new RadioButton();
			_radioButtonHorizontalBox.Text = "HorizontalBox";
			_radioButtonHorizontalBox.Id = "_radioButtonHorizontalBox";

			_radioButtonVerticalBox = new RadioButton();
			_radioButtonVerticalBox.Text = "VerticalBox";
			_radioButtonVerticalBox.Id = "_radioButtonVerticalBox";

			_radioButtonPanel = new RadioButton();
			_radioButtonPanel.Text = "Panel";
			_radioButtonPanel.Id = "_radioButtonPanel";

			_radioButtonScrollPane = new RadioButton();
			_radioButtonScrollPane.Text = "ScrollPane";
			_radioButtonScrollPane.Id = "_radioButtonScrollPane";

			_radioButtonHorizontalSplitPane = new RadioButton();
			_radioButtonHorizontalSplitPane.Text = "HorizontalSplitPane";
			_radioButtonHorizontalSplitPane.Id = "_radioButtonHorizontalSplitPane";

			_radioButtonVerticalSplitPane = new RadioButton();
			_radioButtonVerticalSplitPane.Text = "VerticalSplitPane";
			_radioButtonVerticalSplitPane.Id = "_radioButtonVerticalSplitPane";

			_radioButtonWindow = new RadioButton();
			_radioButtonWindow.Text = "Window";
			_radioButtonWindow.Id = "_radioButtonWindow";

			_radioButtonDialog = new RadioButton();
			_radioButtonDialog.Text = "Dialog";
			_radioButtonDialog.Id = "_radioButtonDialog";

			var verticalBox1 = new VerticalBox();
			verticalBox1.Widgets.Add(_radioButtonGrid);
			verticalBox1.Widgets.Add(_radioButtonHorizontalBox);
			verticalBox1.Widgets.Add(_radioButtonVerticalBox);
			verticalBox1.Widgets.Add(_radioButtonPanel);
			verticalBox1.Widgets.Add(_radioButtonScrollPane);
			verticalBox1.Widgets.Add(_radioButtonHorizontalSplitPane);
			verticalBox1.Widgets.Add(_radioButtonVerticalSplitPane);
			verticalBox1.Widgets.Add(_radioButtonWindow);
			verticalBox1.Widgets.Add(_radioButtonDialog);

			
			Title = "Choose Root Container";
			Left = 431;
			Top = 32;
			Content = verticalBox1;
		}

		
		public RadioButton _radioButtonGrid;
		public RadioButton _radioButtonHorizontalBox;
		public RadioButton _radioButtonVerticalBox;
		public RadioButton _radioButtonPanel;
		public RadioButton _radioButtonScrollPane;
		public RadioButton _radioButtonHorizontalSplitPane;
		public RadioButton _radioButtonVerticalSplitPane;
		public RadioButton _radioButtonWindow;
		public RadioButton _radioButtonDialog;
	}
}