/* Generated by MyraPad at 09.01.2019 1:51:46 */
using Myra.Graphics2D.UI;

namespace MyraPad.UI
{
	public partial class NewProjectWizard: Dialog
	{
		public NewProjectWizard()
		{
			BuildUI();

			_radioButtonGrid.IsPressed = true;
		}
	}
}