/* Generated by MyraPad at 10.01.2020 23:09:59 */
using Myra.Assets;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace MyraPad.UI
{
	partial class StudioWidget: VerticalStackPanel
	{
		private void BuildUI()
		{
			_menuFileNew = new MenuItem();
			_menuFileNew.Text = "&New";
			_menuFileNew.ShortcutText = "Ctrl+N";
			_menuFileNew.Id = "_menuFileNew";

			_menuFileOpen = new MenuItem();
			_menuFileOpen.Text = "&Open";
			_menuFileOpen.ShortcutText = "Ctrl+O";
			_menuFileOpen.Id = "_menuFileOpen";

			_menuFileReload = new MenuItem();
			_menuFileReload.Text = "&Reload";
			_menuFileReload.ShortcutText = "Ctrl+R";
			_menuFileReload.Id = "_menuFileReload";

			_menuFileSave = new MenuItem();
			_menuFileSave.Text = "&Save";
			_menuFileSave.ShortcutText = "Ctrl+S";
			_menuFileSave.Id = "_menuFileSave";

			_menuFileSaveAs = new MenuItem();
			_menuFileSaveAs.Text = "Save &As...";
			_menuFileSaveAs.Id = "_menuFileSaveAs";

			_menuFileExportToCS = new MenuItem();
			_menuFileExportToCS.Text = "&Export To C#...";
			_menuFileExportToCS.ShortcutText = "Ctrl+E";
			_menuFileExportToCS.Id = "_menuFileExportToCS";

			var menuSeparator1 = new MenuSeparator();

			_menuFileLoadStylesheet = new MenuItem();
			_menuFileLoadStylesheet.Text = "&Load Stylesheet";
			_menuFileLoadStylesheet.Id = "_menuFileLoadStylesheet";

			_menuFileResetStylesheet = new MenuItem();
			_menuFileResetStylesheet.Text = "Rese&t Stylesheet";
			_menuFileResetStylesheet.Id = "_menuFileResetStylesheet";

			var menuSeparator2 = new MenuSeparator();

			_menuFileDebugOptions = new MenuItem();
			_menuFileDebugOptions.Text = "&UI Debug Options";
			_menuFileDebugOptions.Id = "_menuFileDebugOptions";

			var menuSeparator3 = new MenuSeparator();

			_menuFileQuit = new MenuItem();
			_menuFileQuit.Text = "&Quit";
			_menuFileQuit.ShortcutText = "Ctrl+Q";
			_menuFileQuit.Id = "_menuFileQuit";

			_menuFile = new MenuItem();
			_menuFile.Text = "&File";
			_menuFile.Id = "_menuFile";
			_menuFile.Items.Add(_menuFileNew);
			_menuFile.Items.Add(_menuFileOpen);
			_menuFile.Items.Add(_menuFileReload);
			_menuFile.Items.Add(_menuFileSave);
			_menuFile.Items.Add(_menuFileSaveAs);
			_menuFile.Items.Add(_menuFileExportToCS);
			_menuFile.Items.Add(menuSeparator1);
			_menuFile.Items.Add(_menuFileLoadStylesheet);
			_menuFile.Items.Add(_menuFileResetStylesheet);
			_menuFile.Items.Add(menuSeparator2);
			_menuFile.Items.Add(_menuFileDebugOptions);
			_menuFile.Items.Add(menuSeparator3);
			_menuFile.Items.Add(_menuFileQuit);

			_menuItemSelectAll = new MenuItem();
			_menuItemSelectAll.Text = "Select &All";
			_menuItemSelectAll.ShortcutText = "Ctrl+A";
			_menuItemSelectAll.Id = "_menuItemSelectAll";

			_menuItemCopy = new MenuItem();
			_menuItemCopy.Text = "&Copy";
			_menuItemCopy.ShortcutText = "Ctrl+Insert, Ctrl+C";
			_menuItemCopy.Id = "_menuItemCopy";

			_menuItemPaste = new MenuItem();
			_menuItemPaste.Text = "&Paste";
			_menuItemPaste.ShortcutText = "Shift+Insert, Ctrl+V";
			_menuItemPaste.Id = "_menuItemPaste";

			var menuSeparator4 = new MenuSeparator();

			_menuEditFormatSource = new MenuItem();
			_menuEditFormatSource.Text = "&Format Source";
			_menuEditFormatSource.ShortcutText = "Ctrl+F";
			_menuEditFormatSource.Id = "_menuEditFormatSource";

			var menuItem1 = new MenuItem();
			menuItem1.Text = "&Edit";
			menuItem1.Items.Add(_menuItemSelectAll);
			menuItem1.Items.Add(_menuItemCopy);
			menuItem1.Items.Add(_menuItemPaste);
			menuItem1.Items.Add(menuSeparator4);
			menuItem1.Items.Add(_menuEditFormatSource);

			_menuHelpAbout = new MenuItem();
			_menuHelpAbout.Text = "&About";
			_menuHelpAbout.Id = "_menuHelpAbout";

			var menuItem2 = new MenuItem();
			menuItem2.Text = "&Help";
			menuItem2.Items.Add(_menuHelpAbout);

			_mainMenu = new HorizontalMenu();
			_mainMenu.Id = "_mainMenu";
			_mainMenu.Items.Add(_menuFile);
			_mainMenu.Items.Add(menuItem1);
			_mainMenu.Items.Add(menuItem2);

			_projectHolder = new Panel();
			_projectHolder.Id = "_projectHolder";

			_textSource = new TextBox();
			_textSource.Multiline = true;
			_textSource.Wrap = true;
			_textSource.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_textSource.GridRow = 2;
			_textSource.Id = "_textSource";

			var scrollViewer1 = new ScrollViewer();
			scrollViewer1.Content = _textSource;

			_leftSplitPane = new VerticalSplitPane();
			_leftSplitPane.Id = "_leftSplitPane";
			_leftSplitPane.Widgets.Add(_projectHolder);
			_leftSplitPane.Widgets.Add(scrollViewer1);

			var horizontalSeparator1 = new HorizontalSeparator();

			_textStatus = new Label();
			_textStatus.Text = "Reloading...";
			_textStatus.Id = "_textStatus";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			verticalStackPanel1.Widgets.Add(_leftSplitPane);
			verticalStackPanel1.Widgets.Add(horizontalSeparator1);
			verticalStackPanel1.Widgets.Add(_textStatus);

			_propertyGridPane = new ScrollViewer();
			_propertyGridPane.Content = null;
			_propertyGridPane.Id = "_propertyGridPane";

			var horizontalSeparator2 = new HorizontalSeparator();

			_textLocation = new Label();
			_textLocation.Text = "Line: 1, Column: 2, Indent: 3";
			_textLocation.Id = "_textLocation";

			var verticalStackPanel2 = new VerticalStackPanel();
			verticalStackPanel2.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			verticalStackPanel2.Widgets.Add(_propertyGridPane);
			verticalStackPanel2.Widgets.Add(horizontalSeparator2);
			verticalStackPanel2.Widgets.Add(_textLocation);

			_topSplitPane = new HorizontalSplitPane();
			_topSplitPane.Id = "_topSplitPane";
			_topSplitPane.Widgets.Add(verticalStackPanel1);
			_topSplitPane.Widgets.Add(verticalStackPanel2);

			
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			Widgets.Add(_mainMenu);
			Widgets.Add(_topSplitPane);
		}

		
		public MenuItem _menuFileNew;
		public MenuItem _menuFileOpen;
		public MenuItem _menuFileReload;
		public MenuItem _menuFileSave;
		public MenuItem _menuFileSaveAs;
		public MenuItem _menuFileExportToCS;
		public MenuItem _menuFileLoadStylesheet;
		public MenuItem _menuFileResetStylesheet;
		public MenuItem _menuFileDebugOptions;
		public MenuItem _menuFileQuit;
		public MenuItem _menuFile;
		public MenuItem _menuItemSelectAll;
		public MenuItem _menuItemCopy;
		public MenuItem _menuItemPaste;
		public MenuItem _menuEditFormatSource;
		public MenuItem _menuHelpAbout;
		public HorizontalMenu _mainMenu;
		public Panel _projectHolder;
		public TextBox _textSource;
		public VerticalSplitPane _leftSplitPane;
		public Label _textStatus;
		public ScrollViewer _propertyGridPane;
		public Label _textLocation;
		public HorizontalSplitPane _topSplitPane;
	}
}