/* Generated by Myra UI Editor at 10/2/2017 12:49:31 AM */
using Myra.Graphics2D.UI;

namespace Myra.Samples.Notepad
{
	public partial class Notepad: Grid
	{
		public Notepad()
		{
			BuildUI();
		}
	}
}