/* Generated by Myra UI Editor at 11/16/2017 2:38:36 AM */
using Myra.Graphics2D.UI;

namespace Myra.Samples.CustomUIStylesheetSample
{
	public partial class AllWidgets: Grid
	{
		public AllWidgets()
		{
			BuildUI();
		}
	}
}