//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myra.Samples.NotepadSample {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Myra.Samples.NotepadSample.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$id&quot;: &quot;1&quot;,
        ///  &quot;$type&quot;: &quot;Myra.Graphics2D.UI.Project, Myra&quot;,
        ///  &quot;Root&quot;: {
        ///    &quot;$id&quot;: &quot;2&quot;,
        ///    &quot;$type&quot;: &quot;Myra.Graphics2D.UI.Grid, Myra&quot;,
        ///    &quot;DrawLines&quot;: false,
        ///    &quot;DrawLinesColor&quot;: {
        ///      &quot;$id&quot;: &quot;3&quot;,
        ///      &quot;$type&quot;: &quot;Microsoft.Xna.Framework.Color, MonoGame.Framework&quot;,
        ///      &quot;B&quot;: 255,
        ///      &quot;G&quot;: 255,
        ///      &quot;R&quot;: 255,
        ///      &quot;A&quot;: 255
        ///    },
        ///    &quot;Widgets&quot;: [
        ///      {
        ///        &quot;$id&quot;: &quot;4&quot;,
        ///        &quot;$type&quot;: &quot;Myra.Graphics2D.UI.HorizontalMenu, Myra&quot;,
        ///        &quot;Items&quot;: [
        ///          {
        ///            &quot;$ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string notepad {
            get {
                return ResourceManager.GetString("notepad", resourceCulture);
            }
        }
    }
}
