/* Generated by MyraPad at 9/8/2026 9:11:09 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Myra.Graphics2D.UI
{
	partial class DebugOptionsWindow: Window
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Draw green frame around every widget";

			_checkBoxWidgetFrames = new CheckButton();
			_checkBoxWidgetFrames.Id = "_checkBoxWidgetFrames";
			_checkBoxWidgetFrames.Content = label1;

			var label2 = new Label();
			label2.Text = "Draw red frame around the keyboard focused widget";

			_checkBoxKeyboardFocusedWidgetFrame = new CheckButton();
			_checkBoxKeyboardFocusedWidgetFrame.Id = "_checkBoxKeyboardFocusedWidgetFrame";
			_checkBoxKeyboardFocusedWidgetFrame.Content = label2;

			var label3 = new Label();
			label3.Text = "Draw yellow frame around the mouse hovered widget";

			_checkBoxMouseInsideWidgetFrame = new CheckButton();
			_checkBoxMouseInsideWidgetFrame.Id = "_checkBoxMouseInsideWidgetFrame";
			_checkBoxMouseInsideWidgetFrame.Content = label3;

			var label4 = new Label();
			label4.Text = "Draw white frame around every TextBox letter glyph";

			_checkBoxGlyphFrames = new CheckButton();
			_checkBoxGlyphFrames.Id = "_checkBoxGlyphFrames";
			_checkBoxGlyphFrames.Content = label4;

			var label5 = new Label();
			label5.Text = "Disable clipping";

			_checkBoxDisableClipping = new CheckButton();
			_checkBoxDisableClipping.Id = "_checkBoxDisableClipping";
			_checkBoxDisableClipping.Content = label5;

			var label6 = new Label();
			label6.Text = "Draw information about the mouse hovered widget";

			_checkBoxDrawMouseHoveredWidgetInfo = new CheckButton();
			_checkBoxDrawMouseHoveredWidgetInfo.Id = "_checkBoxDrawMouseHoveredWidgetInfo";
			_checkBoxDrawMouseHoveredWidgetInfo.Content = label6;

			Root = new VerticalStackPanel();
			Root.Id = "Root";
			Root.Widgets.Add(_checkBoxWidgetFrames);
			Root.Widgets.Add(_checkBoxKeyboardFocusedWidgetFrame);
			Root.Widgets.Add(_checkBoxMouseInsideWidgetFrame);
			Root.Widgets.Add(_checkBoxGlyphFrames);
			Root.Widgets.Add(_checkBoxDisableClipping);
			Root.Widgets.Add(_checkBoxDrawMouseHoveredWidgetInfo);

			
			Title = "Debug Options";
			Left = 534;
			Top = 320;
			Content = Root;
		}

		
		private CheckButton _checkBoxWidgetFrames;
		private CheckButton _checkBoxKeyboardFocusedWidgetFrame;
		private CheckButton _checkBoxMouseInsideWidgetFrame;
		private CheckButton _checkBoxGlyphFrames;
		private CheckButton _checkBoxDisableClipping;
		private CheckButton _checkBoxDrawMouseHoveredWidgetInfo;
		private VerticalStackPanel Root;
	}
}
