/* Generated by MyraPad at 7/15/2021 10:08:22 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace Myra.Graphics2D.UI
{
	partial class DebugOptionsWindow: Window
	{
		private void BuildUI()
		{
			_checkBoxWidgetFrames = new CheckBox();
			_checkBoxWidgetFrames.Text = "Draw green frame around every widget";
			_checkBoxWidgetFrames.Id = "_checkBoxWidgetFrames";

			_checkBoxKeyboardFocusedWidgetFrame = new CheckBox();
			_checkBoxKeyboardFocusedWidgetFrame.Text = "Draw red frame around the keyboard focused widget";
			_checkBoxKeyboardFocusedWidgetFrame.Id = "_checkBoxKeyboardFocusedWidgetFrame";

			_checkBoxMouseInsideWidgetFrame = new CheckBox();
			_checkBoxMouseInsideWidgetFrame.Text = "Draw yellow frame around the mouse hovered widget";
			_checkBoxMouseInsideWidgetFrame.Id = "_checkBoxMouseInsideWidgetFrame";

			_checkBoxGlyphFrames = new CheckBox();
			_checkBoxGlyphFrames.Text = "Draw white frame around every TextBox letter glyph";
			_checkBoxGlyphFrames.Id = "_checkBoxGlyphFrames";

			_checkBoxDisableClipping = new CheckBox();
			_checkBoxDisableClipping.Text = "Disable clipping";
			_checkBoxDisableClipping.Id = "_checkBoxDisableClipping";

			_checkBoxSmoothText = new CheckBox();
			_checkBoxSmoothText.Text = "Smooth text";
			_checkBoxSmoothText.Id = "_checkBoxSmoothText";

			Root = new VerticalStackPanel();
			Root.Id = "Root";
			Root.Widgets.Add(_checkBoxWidgetFrames);
			Root.Widgets.Add(_checkBoxKeyboardFocusedWidgetFrame);
			Root.Widgets.Add(_checkBoxMouseInsideWidgetFrame);
			Root.Widgets.Add(_checkBoxGlyphFrames);
			Root.Widgets.Add(_checkBoxDisableClipping);
			Root.Widgets.Add(_checkBoxSmoothText);

			
			Title = "Debug Options";
			Left = 533;
			Top = 179;
			Content = Root;
		}

		
		public CheckBox _checkBoxWidgetFrames;
		public CheckBox _checkBoxKeyboardFocusedWidgetFrame;
		public CheckBox _checkBoxMouseInsideWidgetFrame;
		public CheckBox _checkBoxGlyphFrames;
		public CheckBox _checkBoxDisableClipping;
		public CheckBox _checkBoxSmoothText;
		public VerticalStackPanel Root;
	}
}
