/* Generated by Myra UI Editor at 10/24/2017 2:47:24 AM */
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;

namespace Myra.Graphics2D.UI
{
	partial class DebugOptionsWidget
	{
		private void BuildUI()
		{
			_checkBoxWidgetFrames = new CheckBox();
			_checkBoxWidgetFrames.Text = "Draw green frame around every widget";
			_checkBoxWidgetFrames.TextColor = Color.White;
			_checkBoxWidgetFrames.ImageWidthHint = 10;
			_checkBoxWidgetFrames.ImageHeightHint = 10;
			_checkBoxWidgetFrames.ImageVisible = true;
			_checkBoxWidgetFrames.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_checkBoxWidgetFrames.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_checkBoxWidgetFrames.Enabled = true;
			_checkBoxWidgetFrames.Id = "_checkBoxWidgetFrames";
			_checkBoxWidgetFrames.XHint = 0;
			_checkBoxWidgetFrames.YHint = 0;
			_checkBoxWidgetFrames.WidthHint = null;
			_checkBoxWidgetFrames.HeightHint = null;
			_checkBoxWidgetFrames.PaddingLeft = 0;
			_checkBoxWidgetFrames.PaddingRight = 0;
			_checkBoxWidgetFrames.PaddingTop = 0;
			_checkBoxWidgetFrames.PaddingBottom = 0;
			_checkBoxWidgetFrames.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			_checkBoxWidgetFrames.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			_checkBoxWidgetFrames.GridPositionX = 0;
			_checkBoxWidgetFrames.GridPositionY = 0;
			_checkBoxWidgetFrames.GridSpanX = 1;
			_checkBoxWidgetFrames.GridSpanY = 1;
			_checkBoxWidgetFrames.Visible = true;
			_checkBoxWidgetFrames.ClipToBounds = false;
			_checkBoxWidgetFrames.CanFocus = false;

			_checkBoxFocusedWidgetFrame = new CheckBox();
			_checkBoxFocusedWidgetFrame.Text = "Draw red frame around the focused widget";
			_checkBoxFocusedWidgetFrame.TextColor = Color.White;
			_checkBoxFocusedWidgetFrame.ImageWidthHint = 10;
			_checkBoxFocusedWidgetFrame.ImageHeightHint = 10;
			_checkBoxFocusedWidgetFrame.ImageVisible = true;
			_checkBoxFocusedWidgetFrame.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_checkBoxFocusedWidgetFrame.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_checkBoxFocusedWidgetFrame.Enabled = true;
			_checkBoxFocusedWidgetFrame.Id = "_checkBoxFocusedWidgetFrame";
			_checkBoxFocusedWidgetFrame.XHint = 0;
			_checkBoxFocusedWidgetFrame.YHint = 0;
			_checkBoxFocusedWidgetFrame.WidthHint = null;
			_checkBoxFocusedWidgetFrame.HeightHint = null;
			_checkBoxFocusedWidgetFrame.PaddingLeft = 0;
			_checkBoxFocusedWidgetFrame.PaddingRight = 0;
			_checkBoxFocusedWidgetFrame.PaddingTop = 0;
			_checkBoxFocusedWidgetFrame.PaddingBottom = 0;
			_checkBoxFocusedWidgetFrame.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			_checkBoxFocusedWidgetFrame.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			_checkBoxFocusedWidgetFrame.GridPositionX = 0;
			_checkBoxFocusedWidgetFrame.GridPositionY = 1;
			_checkBoxFocusedWidgetFrame.GridSpanX = 1;
			_checkBoxFocusedWidgetFrame.GridSpanY = 1;
			_checkBoxFocusedWidgetFrame.Visible = true;
			_checkBoxFocusedWidgetFrame.ClipToBounds = false;
			_checkBoxFocusedWidgetFrame.CanFocus = false;

			_checkBoxGlyphFrames = new CheckBox();
			_checkBoxGlyphFrames.Text = "Draw white frame around every letter glyph";
			_checkBoxGlyphFrames.TextColor = Color.White;
			_checkBoxGlyphFrames.ImageWidthHint = 10;
			_checkBoxGlyphFrames.ImageHeightHint = 10;
			_checkBoxGlyphFrames.ImageVisible = true;
			_checkBoxGlyphFrames.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_checkBoxGlyphFrames.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_checkBoxGlyphFrames.Enabled = true;
			_checkBoxGlyphFrames.Id = "_checkBoxGlyphFrames";
			_checkBoxGlyphFrames.XHint = 0;
			_checkBoxGlyphFrames.YHint = 0;
			_checkBoxGlyphFrames.WidthHint = null;
			_checkBoxGlyphFrames.HeightHint = null;
			_checkBoxGlyphFrames.PaddingLeft = 0;
			_checkBoxGlyphFrames.PaddingRight = 0;
			_checkBoxGlyphFrames.PaddingTop = 0;
			_checkBoxGlyphFrames.PaddingBottom = 0;
			_checkBoxGlyphFrames.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			_checkBoxGlyphFrames.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			_checkBoxGlyphFrames.GridPositionX = 0;
			_checkBoxGlyphFrames.GridPositionY = 2;
			_checkBoxGlyphFrames.GridSpanX = 1;
			_checkBoxGlyphFrames.GridSpanY = 1;
			_checkBoxGlyphFrames.Visible = true;
			_checkBoxGlyphFrames.ClipToBounds = false;
			_checkBoxGlyphFrames.CanFocus = false;

			_checkBoxDisableClipping = new CheckBox();
			_checkBoxDisableClipping.Text = "Disable clipping";
			_checkBoxDisableClipping.TextColor = Color.White;
			_checkBoxDisableClipping.ImageWidthHint = 10;
			_checkBoxDisableClipping.ImageHeightHint = 10;
			_checkBoxDisableClipping.ImageVisible = true;
			_checkBoxDisableClipping.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_checkBoxDisableClipping.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_checkBoxDisableClipping.Enabled = true;
			_checkBoxDisableClipping.Id = "_checkBoxDisableClipping";
			_checkBoxDisableClipping.XHint = 0;
			_checkBoxDisableClipping.YHint = 0;
			_checkBoxDisableClipping.WidthHint = null;
			_checkBoxDisableClipping.HeightHint = null;
			_checkBoxDisableClipping.PaddingLeft = 0;
			_checkBoxDisableClipping.PaddingRight = 0;
			_checkBoxDisableClipping.PaddingTop = 0;
			_checkBoxDisableClipping.PaddingBottom = 0;
			_checkBoxDisableClipping.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			_checkBoxDisableClipping.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			_checkBoxDisableClipping.GridPositionX = 0;
			_checkBoxDisableClipping.GridPositionY = 3;
			_checkBoxDisableClipping.GridSpanX = 1;
			_checkBoxDisableClipping.GridSpanY = 1;
			_checkBoxDisableClipping.Visible = true;
			_checkBoxDisableClipping.ClipToBounds = false;
			_checkBoxDisableClipping.CanFocus = false;

			
			DrawLines = false;
			DrawLinesColor = Color.White;
			ColumnSpacing = 0;
			RowSpacing = 0;
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Auto,
				Value = 1,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Auto,
				Value = 1,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Auto,
				Value = 1,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Auto,
				Value = 1,
			});
			TotalRowsPart = null;
			TotalColumnsPart = null;
			Enabled = true;
			Id = "Root";
			XHint = 0;
			YHint = 0;
			WidthHint = null;
			HeightHint = null;
			PaddingLeft = 0;
			PaddingRight = 0;
			PaddingTop = 0;
			PaddingBottom = 0;
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			GridPositionX = 0;
			GridPositionY = 0;
			GridSpanX = 1;
			GridSpanY = 1;
			Visible = true;
			ClipToBounds = false;
			CanFocus = false;
			Widgets.Add(_checkBoxWidgetFrames);
			Widgets.Add(_checkBoxFocusedWidgetFrame);
			Widgets.Add(_checkBoxGlyphFrames);
			Widgets.Add(_checkBoxDisableClipping);
		}

		
		public CheckBox _checkBoxWidgetFrames;
		public CheckBox _checkBoxFocusedWidgetFrame;
		public CheckBox _checkBoxGlyphFrames;
		public CheckBox _checkBoxDisableClipping;
	}
}