/* Generated by Myra UI Editor at 27.12.2018 23:54:52 */
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;

namespace Myra.Graphics2D.UI
{
	partial class DebugOptionsDialog
	{
		private void BuildUI()
		{
			_checkBoxWidgetFrames = new CheckBox();
			_checkBoxWidgetFrames.Text = "Draw green frame around every widget";
			_checkBoxWidgetFrames.ImageWidth = 10;
			_checkBoxWidgetFrames.ImageHeight = 10;
			_checkBoxWidgetFrames.Id = "_checkBoxWidgetFrames";

			_checkBoxFocusedWidgetFrame = new CheckBox();
			_checkBoxFocusedWidgetFrame.Text = "Draw red frame around the focused widget";
			_checkBoxFocusedWidgetFrame.ImageWidth = 10;
			_checkBoxFocusedWidgetFrame.ImageHeight = 10;
			_checkBoxFocusedWidgetFrame.Id = "_checkBoxFocusedWidgetFrame";
			_checkBoxFocusedWidgetFrame.GridPositionY = 1;

			_checkBoxGlyphFrames = new CheckBox();
			_checkBoxGlyphFrames.Text = "Draw white frame around every letter glyph";
			_checkBoxGlyphFrames.ImageWidth = 10;
			_checkBoxGlyphFrames.ImageHeight = 10;
			_checkBoxGlyphFrames.Id = "_checkBoxGlyphFrames";
			_checkBoxGlyphFrames.GridPositionY = 2;

			_checkBoxDisableClipping = new CheckBox();
			_checkBoxDisableClipping.Text = "Disable clipping";
			_checkBoxDisableClipping.ImageWidth = 10;
			_checkBoxDisableClipping.ImageHeight = 10;
			_checkBoxDisableClipping.Id = "_checkBoxDisableClipping";
			_checkBoxDisableClipping.GridPositionY = 3;

			Root = new Grid();
			Root.RowsProportions.Add(new Grid.Proportion());
			Root.RowsProportions.Add(new Grid.Proportion());
			Root.RowsProportions.Add(new Grid.Proportion());
			Root.RowsProportions.Add(new Grid.Proportion());
			Root.Id = "Root";
			Root.GridPositionY = 1;
			Root.Widgets.Add(_checkBoxWidgetFrames);
			Root.Widgets.Add(_checkBoxFocusedWidgetFrame);
			Root.Widgets.Add(_checkBoxGlyphFrames);
			Root.Widgets.Add(_checkBoxDisableClipping);

			
			Title = "Debug Options";
			Left = 279;
			Top = 312;
			Content = Root;
		}

		
		public CheckBox _checkBoxWidgetFrames;
		public CheckBox _checkBoxFocusedWidgetFrame;
		public CheckBox _checkBoxGlyphFrames;
		public CheckBox _checkBoxDisableClipping;
		public Grid Root;
	}
}