/* Generated by MyraPad at 7/20/2026 12:10:10 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Myra.Samples
{
	partial class MainForm: VerticalStackPanel
	{
		private void BuildUI()
		{
			_labelIndex = new Label();
			_labelIndex.Text = "10";
			_labelIndex.Id = "_labelIndex";

			var verticalSeparator1 = new VerticalSeparator();

			_labelCustomerId = new Label();
			_labelCustomerId.Text = "436b9c41cfb1fa3";
			_labelCustomerId.Id = "_labelCustomerId";

			var verticalSeparator2 = new VerticalSeparator();

			_labelFirstName = new Label();
			_labelFirstName.Text = "Brendan";
			_labelFirstName.Id = "_labelFirstName";

			var verticalSeparator3 = new VerticalSeparator();

			_labelLastName = new Label();
			_labelLastName.Text = "Franco";
			_labelLastName.Id = "_labelLastName";

			var verticalSeparator4 = new VerticalSeparator();

			_labelCompany = new Label();
			_labelCompany.Text = "Schaefer, Blair and Shaffer";
			_labelCompany.Id = "_labelCompany";

			var verticalSeparator5 = new VerticalSeparator();

			_labelCity = new Label();
			_labelCity.Text = "New Rickey";
			_labelCity.Id = "_labelCity";

			var verticalSeparator6 = new VerticalSeparator();

			_labelCountry = new Label();
			_labelCountry.Text = "Ukraine";
			_labelCountry.Id = "_labelCountry";

			var verticalSeparator7 = new VerticalSeparator();

			_labelPhone1 = new Label();
			_labelPhone1.Text = "001-315-224-3556";
			_labelPhone1.Id = "_labelPhone1";

			var verticalSeparator8 = new VerticalSeparator();

			_labelPhone2 = new Label();
			_labelPhone2.Text = "254-621-7128x7573";
			_labelPhone2.Id = "_labelPhone2";

			var verticalSeparator9 = new VerticalSeparator();

			_labelEmail = new Label();
			_labelEmail.Text = "kentryan@stone-oneill.com";
			_labelEmail.Id = "_labelEmail";

			var verticalSeparator10 = new VerticalSeparator();

			_labelSubscriptionDate = new Label();
			_labelSubscriptionDate.Text = "2021-06-29";
			_labelSubscriptionDate.Id = "_labelSubscriptionDate";

			var verticalSeparator11 = new VerticalSeparator();

			_labelWebsite = new Label();
			_labelWebsite.Text = "http://ruiz.com/";
			_labelWebsite.Id = "_labelWebsite";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 4;
			horizontalStackPanel1.Widgets.Add(_labelIndex);
			horizontalStackPanel1.Widgets.Add(verticalSeparator1);
			horizontalStackPanel1.Widgets.Add(_labelCustomerId);
			horizontalStackPanel1.Widgets.Add(verticalSeparator2);
			horizontalStackPanel1.Widgets.Add(_labelFirstName);
			horizontalStackPanel1.Widgets.Add(verticalSeparator3);
			horizontalStackPanel1.Widgets.Add(_labelLastName);
			horizontalStackPanel1.Widgets.Add(verticalSeparator4);
			horizontalStackPanel1.Widgets.Add(_labelCompany);
			horizontalStackPanel1.Widgets.Add(verticalSeparator5);
			horizontalStackPanel1.Widgets.Add(_labelCity);
			horizontalStackPanel1.Widgets.Add(verticalSeparator6);
			horizontalStackPanel1.Widgets.Add(_labelCountry);
			horizontalStackPanel1.Widgets.Add(verticalSeparator7);
			horizontalStackPanel1.Widgets.Add(_labelPhone1);
			horizontalStackPanel1.Widgets.Add(verticalSeparator8);
			horizontalStackPanel1.Widgets.Add(_labelPhone2);
			horizontalStackPanel1.Widgets.Add(verticalSeparator9);
			horizontalStackPanel1.Widgets.Add(_labelEmail);
			horizontalStackPanel1.Widgets.Add(verticalSeparator10);
			horizontalStackPanel1.Widgets.Add(_labelSubscriptionDate);
			horizontalStackPanel1.Widgets.Add(verticalSeparator11);
			horizontalStackPanel1.Widgets.Add(_labelWebsite);

			var horizontalSeparator1 = new HorizontalSeparator();

			_panelDataGrid = new Panel();
			_panelDataGrid.Id = "_panelDataGrid";

			_propertyGrid = new PropertyGrid();
			_propertyGrid.Id = "_propertyGrid";

			var scrollViewer1 = new ScrollViewer();
			scrollViewer1.ShowHorizontalScrollBar = false;
			scrollViewer1.Content = _propertyGrid;

			_splitPane = new HorizontalSplitPane();
			_splitPane.Id = "_splitPane";
			StackPanel.SetProportionType(_splitPane, Myra.Graphics2D.UI.ProportionType.Fill);
			_splitPane.Widgets.Add(_panelDataGrid);
			_splitPane.Widgets.Add(scrollViewer1);

			
			Widgets.Add(horizontalStackPanel1);
			Widgets.Add(horizontalSeparator1);
			Widgets.Add(_splitPane);
		}

		
		public Label _labelIndex;
		public Label _labelCustomerId;
		public Label _labelFirstName;
		public Label _labelLastName;
		public Label _labelCompany;
		public Label _labelCity;
		public Label _labelCountry;
		public Label _labelPhone1;
		public Label _labelPhone2;
		public Label _labelEmail;
		public Label _labelSubscriptionDate;
		public Label _labelWebsite;
		public Panel _panelDataGrid;
		public PropertyGrid _propertyGrid;
		public HorizontalSplitPane _splitPane;
	}
}
