/* Generated by MyraPad at 7/20/2026 5:48:42 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Myra.Samples
{
	partial class MainForm: VerticalStackPanel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Show Grid Lines";

			_checkShowGridLines = new CheckButton();
			_checkShowGridLines.Id = "_checkShowGridLines";
			_checkShowGridLines.Content = label1;

			var verticalSeparator1 = new VerticalSeparator();

			var label2 = new Label();
			label2.Text = "ResizableColumns";

			_checkResizableColumns = new CheckButton();
			_checkResizableColumns.Id = "_checkResizableColumns";
			_checkResizableColumns.Content = label2;

			var verticalSeparator2 = new VerticalSeparator();

			var label3 = new Label();
			label3.Text = "Has Header";

			_checkHasHeader = new CheckButton();
			_checkHasHeader.Id = "_checkHasHeader";
			_checkHasHeader.Content = label3;

			var verticalSeparator3 = new VerticalSeparator();

			var label4 = new Label();
			label4.Text = "Has Index Column";

			_checkHasIndexColumn = new CheckButton();
			_checkHasIndexColumn.Id = "_checkHasIndexColumn";
			_checkHasIndexColumn.Content = label4;

			var verticalSeparator4 = new VerticalSeparator();

			var label5 = new Label();
			label5.Text = "Sortable Headers";

			_checkSortableHeaders = new CheckButton();
			_checkSortableHeaders.Id = "_checkSortableHeaders";
			_checkSortableHeaders.Content = label5;

			var verticalSeparator5 = new VerticalSeparator();

			var label6 = new Label();
			label6.Text = "Has Filter";

			_checkHasFilter = new CheckButton();
			_checkHasFilter.Id = "_checkHasFilter";
			_checkHasFilter.Content = label6;

			var verticalSeparator6 = new VerticalSeparator();

			var label7 = new Label();
			label7.Text = "Fill Column:";

			var label8 = new Label();

			var label9 = new Label();
			label9.Text = "First Name";

			var label10 = new Label();
			label10.Text = "Last Name";

			var label11 = new Label();
			label11.Text = "Company";

			var label12 = new Label();
			label12.Text = "City";

			var label13 = new Label();
			label13.Text = "Country";

			var label14 = new Label();
			label14.Text = "Email";

			var label15 = new Label();
			label15.Text = "Phone 1";

			_comboFillColumn = new ComboView();
			_comboFillColumn.Id = "_comboFillColumn";
			_comboFillColumn.Widgets.Add(label8);
			_comboFillColumn.Widgets.Add(label9);
			_comboFillColumn.Widgets.Add(label10);
			_comboFillColumn.Widgets.Add(label11);
			_comboFillColumn.Widgets.Add(label12);
			_comboFillColumn.Widgets.Add(label13);
			_comboFillColumn.Widgets.Add(label14);
			_comboFillColumn.Widgets.Add(label15);

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 4;
			horizontalStackPanel1.Widgets.Add(label7);
			horizontalStackPanel1.Widgets.Add(_comboFillColumn);

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Spacing = 4;
			horizontalStackPanel2.Widgets.Add(_checkShowGridLines);
			horizontalStackPanel2.Widgets.Add(verticalSeparator1);
			horizontalStackPanel2.Widgets.Add(_checkResizableColumns);
			horizontalStackPanel2.Widgets.Add(verticalSeparator2);
			horizontalStackPanel2.Widgets.Add(_checkHasHeader);
			horizontalStackPanel2.Widgets.Add(verticalSeparator3);
			horizontalStackPanel2.Widgets.Add(_checkHasIndexColumn);
			horizontalStackPanel2.Widgets.Add(verticalSeparator4);
			horizontalStackPanel2.Widgets.Add(_checkSortableHeaders);
			horizontalStackPanel2.Widgets.Add(verticalSeparator5);
			horizontalStackPanel2.Widgets.Add(_checkHasFilter);
			horizontalStackPanel2.Widgets.Add(verticalSeparator6);
			horizontalStackPanel2.Widgets.Add(horizontalStackPanel1);

			var horizontalSeparator1 = new HorizontalSeparator();

			_panelDataGrid = new Panel();
			_panelDataGrid.Id = "_panelDataGrid";

			_labelIndex = new Label();
			_labelIndex.Text = "10";
			_labelIndex.Id = "_labelIndex";

			_labelCustomerId = new Label();
			_labelCustomerId.Text = "436b9c41cfb1fa3";
			_labelCustomerId.Id = "_labelCustomerId";

			_labelFirstName = new Label();
			_labelFirstName.Text = "Brendan";
			_labelFirstName.Id = "_labelFirstName";

			_labelLastName = new Label();
			_labelLastName.Text = "Franco";
			_labelLastName.Id = "_labelLastName";

			_labelCompany = new Label();
			_labelCompany.Text = "Schaefer, Blair and Shaffer";
			_labelCompany.Id = "_labelCompany";

			_labelCity = new Label();
			_labelCity.Text = "New Rickey";
			_labelCity.Id = "_labelCity";

			_labelCountry = new Label();
			_labelCountry.Text = "Ukraine";
			_labelCountry.Id = "_labelCountry";

			_labelPhone1 = new Label();
			_labelPhone1.Text = "001-315-224-3556";
			_labelPhone1.Id = "_labelPhone1";

			_labelPhone2 = new Label();
			_labelPhone2.Text = "254-621-7128x7573";
			_labelPhone2.Id = "_labelPhone2";

			_labelEmail = new Label();
			_labelEmail.Text = "kentryan@stone-oneill.com";
			_labelEmail.Id = "_labelEmail";

			_labelSubscriptionDate = new Label();
			_labelSubscriptionDate.Text = "2021-06-29";
			_labelSubscriptionDate.Id = "_labelSubscriptionDate";

			_labelWebsite = new Label();
			_labelWebsite.Text = "http://ruiz.com/";
			_labelWebsite.Id = "_labelWebsite";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Widgets.Add(_labelIndex);
			verticalStackPanel1.Widgets.Add(_labelCustomerId);
			verticalStackPanel1.Widgets.Add(_labelFirstName);
			verticalStackPanel1.Widgets.Add(_labelLastName);
			verticalStackPanel1.Widgets.Add(_labelCompany);
			verticalStackPanel1.Widgets.Add(_labelCity);
			verticalStackPanel1.Widgets.Add(_labelCountry);
			verticalStackPanel1.Widgets.Add(_labelPhone1);
			verticalStackPanel1.Widgets.Add(_labelPhone2);
			verticalStackPanel1.Widgets.Add(_labelEmail);
			verticalStackPanel1.Widgets.Add(_labelSubscriptionDate);
			verticalStackPanel1.Widgets.Add(_labelWebsite);

			_splitPane = new HorizontalSplitPane();
			_splitPane.Id = "_splitPane";
			StackPanel.SetProportionType(_splitPane, Myra.Graphics2D.UI.ProportionType.Fill);
			_splitPane.Widgets.Add(_panelDataGrid);
			_splitPane.Widgets.Add(verticalStackPanel1);

			
			Widgets.Add(horizontalStackPanel2);
			Widgets.Add(horizontalSeparator1);
			Widgets.Add(_splitPane);
		}

		
		public CheckButton _checkShowGridLines;
		public CheckButton _checkResizableColumns;
		public CheckButton _checkHasHeader;
		public CheckButton _checkHasIndexColumn;
		public CheckButton _checkSortableHeaders;
		public CheckButton _checkHasFilter;
		public ComboView _comboFillColumn;
		public Panel _panelDataGrid;
		public Label _labelIndex;
		public Label _labelCustomerId;
		public Label _labelFirstName;
		public Label _labelLastName;
		public Label _labelCompany;
		public Label _labelCity;
		public Label _labelCountry;
		public Label _labelPhone1;
		public Label _labelPhone2;
		public Label _labelEmail;
		public Label _labelSubscriptionDate;
		public Label _labelWebsite;
		public HorizontalSplitPane _splitPane;
	}
}
