/* Generated by MyraPad at 8/8/2026 1:40:30 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Myra.Samples
{
	partial class MainForm: VerticalStackPanel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Show Grid Lines";

			_checkShowGridLines = new CheckButton();
			_checkShowGridLines.Id = "_checkShowGridLines";
			_checkShowGridLines.Content = label1;

			var verticalSeparator1 = new VerticalSeparator();

			var label2 = new Label();
			label2.Text = "ResizableColumns";

			_checkResizableColumns = new CheckButton();
			_checkResizableColumns.Id = "_checkResizableColumns";
			_checkResizableColumns.Content = label2;

			var verticalSeparator2 = new VerticalSeparator();

			var label3 = new Label();
			label3.Text = "Has Header";

			_checkHasHeader = new CheckButton();
			_checkHasHeader.Id = "_checkHasHeader";
			_checkHasHeader.Content = label3;

			var verticalSeparator3 = new VerticalSeparator();

			var label4 = new Label();
			label4.Text = "Has Index Column";

			_checkHasIndexColumn = new CheckButton();
			_checkHasIndexColumn.Id = "_checkHasIndexColumn";
			_checkHasIndexColumn.Content = label4;

			var verticalSeparator4 = new VerticalSeparator();

			var label5 = new Label();
			label5.Text = "Sortable Headers";

			_checkSortableHeaders = new CheckButton();
			_checkSortableHeaders.Id = "_checkSortableHeaders";
			_checkSortableHeaders.Content = label5;

			var verticalSeparator5 = new VerticalSeparator();

			var label6 = new Label();
			label6.Text = "Has Filter";

			_checkHasFilter = new CheckButton();
			_checkHasFilter.Id = "_checkHasFilter";
			_checkHasFilter.Content = label6;

			var verticalSeparator6 = new VerticalSeparator();

			var label7 = new Label();
			label7.Text = "Fill Column:";

			var label8 = new Label();

			var label9 = new Label();
			label9.Text = "First Name";

			var label10 = new Label();
			label10.Text = "Last Name";

			var label11 = new Label();
			label11.Text = "Company";

			var label12 = new Label();
			label12.Text = "City";

			var label13 = new Label();
			label13.Text = "Country";

			var label14 = new Label();
			label14.Text = "Email";

			var label15 = new Label();
			label15.Text = "Phone 1";

			_comboFillColumn = new ComboView();
			_comboFillColumn.Id = "_comboFillColumn";
			_comboFillColumn.Widgets.Add(label8);
			_comboFillColumn.Widgets.Add(label9);
			_comboFillColumn.Widgets.Add(label10);
			_comboFillColumn.Widgets.Add(label11);
			_comboFillColumn.Widgets.Add(label12);
			_comboFillColumn.Widgets.Add(label13);
			_comboFillColumn.Widgets.Add(label14);
			_comboFillColumn.Widgets.Add(label15);

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 4;
			horizontalStackPanel1.Widgets.Add(label7);
			horizontalStackPanel1.Widgets.Add(_comboFillColumn);

			var label16 = new Label();
			label16.Text = "Header Alignment:";

			var label17 = new Label();
			label17.Text = "Left";

			var label18 = new Label();
			label18.Text = "Center";

			var label19 = new Label();
			label19.Text = "Right";

			_comboHeaderAlignment = new ComboView();
			_comboHeaderAlignment.Id = "_comboHeaderAlignment";
			_comboHeaderAlignment.Widgets.Add(label17);
			_comboHeaderAlignment.Widgets.Add(label18);
			_comboHeaderAlignment.Widgets.Add(label19);

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Spacing = 4;
			horizontalStackPanel2.Widgets.Add(label16);
			horizontalStackPanel2.Widgets.Add(_comboHeaderAlignment);

			var label20 = new Label();
			label20.Text = "Cell Alignment:";

			var label21 = new Label();
			label21.Text = "Left";

			var label22 = new Label();
			label22.Text = "Center";

			var label23 = new Label();
			label23.Text = "Right";

			_comboCellAlignment = new ComboView();
			_comboCellAlignment.Id = "_comboCellAlignment";
			_comboCellAlignment.Widgets.Add(label21);
			_comboCellAlignment.Widgets.Add(label22);
			_comboCellAlignment.Widgets.Add(label23);

			var horizontalStackPanel3 = new HorizontalStackPanel();
			horizontalStackPanel3.Spacing = 4;
			horizontalStackPanel3.Widgets.Add(label20);
			horizontalStackPanel3.Widgets.Add(_comboCellAlignment);

			var horizontalStackPanel4 = new HorizontalStackPanel();
			horizontalStackPanel4.Spacing = 4;
			horizontalStackPanel4.Widgets.Add(_checkShowGridLines);
			horizontalStackPanel4.Widgets.Add(verticalSeparator1);
			horizontalStackPanel4.Widgets.Add(_checkResizableColumns);
			horizontalStackPanel4.Widgets.Add(verticalSeparator2);
			horizontalStackPanel4.Widgets.Add(_checkHasHeader);
			horizontalStackPanel4.Widgets.Add(verticalSeparator3);
			horizontalStackPanel4.Widgets.Add(_checkHasIndexColumn);
			horizontalStackPanel4.Widgets.Add(verticalSeparator4);
			horizontalStackPanel4.Widgets.Add(_checkSortableHeaders);
			horizontalStackPanel4.Widgets.Add(verticalSeparator5);
			horizontalStackPanel4.Widgets.Add(_checkHasFilter);
			horizontalStackPanel4.Widgets.Add(verticalSeparator6);
			horizontalStackPanel4.Widgets.Add(horizontalStackPanel1);
			horizontalStackPanel4.Widgets.Add(horizontalStackPanel2);
			horizontalStackPanel4.Widgets.Add(horizontalStackPanel3);

			var horizontalSeparator1 = new HorizontalSeparator();

			_panelDataGrid = new Panel();
			_panelDataGrid.Id = "_panelDataGrid";

			_propertyGrid = new PropertyGrid();
			_propertyGrid.Id = "_propertyGrid";

			_splitPane = new HorizontalSplitPane();
			_splitPane.Id = "_splitPane";
			StackPanel.SetProportionType(_splitPane, Myra.Graphics2D.UI.ProportionType.Fill);
			_splitPane.Widgets.Add(_panelDataGrid);
			_splitPane.Widgets.Add(_propertyGrid);

			
			Widgets.Add(horizontalStackPanel4);
			Widgets.Add(horizontalSeparator1);
			Widgets.Add(_splitPane);
		}

		
		public CheckButton _checkShowGridLines;
		public CheckButton _checkResizableColumns;
		public CheckButton _checkHasHeader;
		public CheckButton _checkHasIndexColumn;
		public CheckButton _checkSortableHeaders;
		public CheckButton _checkHasFilter;
		public ComboView _comboFillColumn;
		public ComboView _comboHeaderAlignment;
		public ComboView _comboCellAlignment;
		public Panel _panelDataGrid;
		public PropertyGrid _propertyGrid;
		public HorizontalSplitPane _splitPane;
	}
}
