/* Generated by Myra UI Editor at 09.01.2019 1:51:46 */
using Myra.Graphics2D.UI;

namespace Myra.UIEditor.UI
{
	public partial class NewProjectWizard: Dialog
	{
		public NewProjectWizard()
		{
			BuildUI();
		}
	}
}