/* Generated by Myra UI Editor at 09.01.2019 1:51:46 */
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;

namespace Myra.UIEditor.UI
{
	partial class NewProjectWizard
	{
		private void BuildUI()
		{
			_radioButtonGrid = new RadioButton();
			_radioButtonGrid.Text = "Grid";
			_radioButtonGrid.ImageWidth = 8;
			_radioButtonGrid.ImageHeight = 8;
			_radioButtonGrid.Id = "_radioButtonGrid";

			_radioButtonPanel = new RadioButton();
			_radioButtonPanel.Text = "Panel";
			_radioButtonPanel.ImageWidth = 8;
			_radioButtonPanel.ImageHeight = 8;
			_radioButtonPanel.Id = "_radioButtonPanel";
			_radioButtonPanel.GridPositionY = 1;

			_radioButtonScrollPane = new RadioButton();
			_radioButtonScrollPane.Text = "ScrollPane";
			_radioButtonScrollPane.ImageWidth = 8;
			_radioButtonScrollPane.ImageHeight = 8;
			_radioButtonScrollPane.Id = "_radioButtonScrollPane";
			_radioButtonScrollPane.GridPositionY = 2;

			_radioButtonHorizontalSplitPane = new RadioButton();
			_radioButtonHorizontalSplitPane.Text = "HorizontalSplitPane";
			_radioButtonHorizontalSplitPane.ImageWidth = 8;
			_radioButtonHorizontalSplitPane.ImageHeight = 8;
			_radioButtonHorizontalSplitPane.Id = "_radioButtonHorizontalSplitPane";
			_radioButtonHorizontalSplitPane.GridPositionY = 3;

			_radioButtonVerticalSplitPane = new RadioButton();
			_radioButtonVerticalSplitPane.Text = "VerticalSplitPane";
			_radioButtonVerticalSplitPane.ImageWidth = 8;
			_radioButtonVerticalSplitPane.ImageHeight = 8;
			_radioButtonVerticalSplitPane.Id = "_radioButtonVerticalSplitPane";
			_radioButtonVerticalSplitPane.GridPositionY = 4;

			_radioButtonWindow = new RadioButton();
			_radioButtonWindow.Text = "Window";
			_radioButtonWindow.ImageWidth = 8;
			_radioButtonWindow.ImageHeight = 8;
			_radioButtonWindow.Id = "_radioButtonWindow";
			_radioButtonWindow.GridPositionY = 5;

			_radioButtonDialog = new RadioButton();
			_radioButtonDialog.Text = "Dialog";
			_radioButtonDialog.ImageWidth = 8;
			_radioButtonDialog.ImageHeight = 8;
			_radioButtonDialog.Id = "_radioButtonDialog";
			_radioButtonDialog.GridPositionY = 6;

			var grid1 = new Grid();
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.GridPositionY = 1;
			grid1.Widgets.Add(_radioButtonGrid);
			grid1.Widgets.Add(_radioButtonPanel);
			grid1.Widgets.Add(_radioButtonScrollPane);
			grid1.Widgets.Add(_radioButtonHorizontalSplitPane);
			grid1.Widgets.Add(_radioButtonVerticalSplitPane);
			grid1.Widgets.Add(_radioButtonWindow);
			grid1.Widgets.Add(_radioButtonDialog);

			
			Title = "Choose Root Container";
			Left = 229;
			Top = 265;
			Content = grid1;
		}

		
		public RadioButton _radioButtonGrid;
		public RadioButton _radioButtonPanel;
		public RadioButton _radioButtonScrollPane;
		public RadioButton _radioButtonHorizontalSplitPane;
		public RadioButton _radioButtonVerticalSplitPane;
		public RadioButton _radioButtonWindow;
		public RadioButton _radioButtonDialog;
	}
}