/* Generated by MyraPad at 12/6/2023 3:29:08 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Myra.Samples.AllWidgets
{
	partial class AllWidgets: Panel
	{
		private void BuildUI()
		{
			_menuItemOpenFile = new MenuItem();
			_menuItemOpenFile.Text = "&Open";
			_menuItemOpenFile.ShortcutText = "Ctrl+O";
			_menuItemOpenFile.Id = "_menuItemOpenFile";

			_menuItemSaveFile = new MenuItem();
			_menuItemSaveFile.Text = "&Save";
			_menuItemSaveFile.ShortcutText = "Ctrl+S";
			_menuItemSaveFile.Id = "_menuItemSaveFile";

			_menuItemChooseFolder = new MenuItem();
			_menuItemChooseFolder.Text = "Choose Fol&der";
			_menuItemChooseFolder.ShortcutText = "Ctrl+D";
			_menuItemChooseFolder.Id = "_menuItemChooseFolder";

			_menuItemChooseColor = new MenuItem();
			_menuItemChooseColor.Text = "Choose Co&lor";
			_menuItemChooseColor.ShortcutText = "Ctrl+L";
			_menuItemChooseColor.Id = "_menuItemChooseColor";

			var menuSeparator1 = new MenuSeparator();

			_menuItemQuit = new MenuItem();
			_menuItemQuit.Text = "&Quit";
			_menuItemQuit.ShortcutText = "Ctrl+Q";
			_menuItemQuit.Id = "_menuItemQuit";

			_menuFile = new MenuItem();
			_menuFile.Text = "&File";
			_menuFile.Id = "_menuFile";
			_menuFile.Items.Add(_menuItemOpenFile);
			_menuFile.Items.Add(_menuItemSaveFile);
			_menuFile.Items.Add(_menuItemChooseFolder);
			_menuFile.Items.Add(_menuItemChooseColor);
			_menuFile.Items.Add(menuSeparator1);
			_menuFile.Items.Add(_menuItemQuit);

			_menuItemCopy = new MenuItem();
			_menuItemCopy.Text = "&Copy";
			_menuItemCopy.ShortcutText = "Ctrl+Insert, Ctrl+C";
			_menuItemCopy.Id = "_menuItemCopy";

			_menuItemPaste = new MenuItem();
			_menuItemPaste.Text = "&Paste";
			_menuItemPaste.ShortcutText = "Shift+Insert, Ctrl+V";
			_menuItemPaste.Id = "_menuItemPaste";

			var menuSeparator2 = new MenuSeparator();

			_menuItemUndo = new MenuItem();
			_menuItemUndo.Text = "&Undo";
			_menuItemUndo.ShortcutText = "Ctrl+Z";
			_menuItemUndo.Id = "_menuItemUndo";

			_menuItemRedo = new MenuItem();
			_menuItemRedo.Text = "&Redo";
			_menuItemRedo.ShortcutText = "Ctrl+Y";
			_menuItemRedo.Id = "_menuItemRedo";

			_menuEdit = new MenuItem();
			_menuEdit.Text = "&Edit";
			_menuEdit.Id = "_menuEdit";
			_menuEdit.Items.Add(_menuItemCopy);
			_menuEdit.Items.Add(_menuItemPaste);
			_menuEdit.Items.Add(menuSeparator2);
			_menuEdit.Items.Add(_menuItemUndo);
			_menuEdit.Items.Add(_menuItemRedo);

			_menuItemAbout = new MenuItem();
			_menuItemAbout.Text = "&About";
			_menuItemAbout.Id = "_menuItemAbout";

			_menuHelp = new MenuItem();
			_menuHelp.Text = "&Help";
			_menuHelp.Id = "_menuHelp";
			_menuHelp.Items.Add(_menuItemAbout);

			_mainMenu = new HorizontalMenu();
			_mainMenu.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_mainMenu.Id = "_mainMenu";
			_mainMenu.Items.Add(_menuFile);
			_mainMenu.Items.Add(_menuEdit);
			_mainMenu.Items.Add(_menuHelp);

			var label1 = new Label();
			label1.Text = "Button:";

			_imageSaveFile = new Image();
			_imageSaveFile.Id = "_imageSaveFile";

			var label2 = new Label();
			label2.Text = "Save File";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Widgets.Add(_imageSaveFile);
			horizontalStackPanel1.Widgets.Add(label2);

			_buttonSaveFile = new Button();
			_buttonSaveFile.Padding = new Thickness(8, 0);
			_buttonSaveFile.Tooltip = "E=mc/v[-8]2/n/vdMass–energy equivalence.";
			_buttonSaveFile.Id = "_buttonSaveFile";
			Grid.SetColumn(_buttonSaveFile, 1);
			_buttonSaveFile.Content = horizontalStackPanel1;

			_textSaveFile = new TextBox();
			_textSaveFile.Id = "_textSaveFile";
			Grid.SetColumn(_textSaveFile, 2);

			var label3 = new Label();
			label3.Text = "Another Button:";
			Grid.SetRow(label3, 1);

			_imageOpenFile = new Image();
			_imageOpenFile.Id = "_imageOpenFile";

			var label4 = new Label();
			label4.Text = "Open File";

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Widgets.Add(_imageOpenFile);
			horizontalStackPanel2.Widgets.Add(label4);

			_buttonOpenFile = new Button();
			_buttonOpenFile.Padding = new Thickness(8, 0);
			_buttonOpenFile.Tooltip = "Tooltip 2";
			_buttonOpenFile.Id = "_buttonOpenFile";
			Grid.SetColumn(_buttonOpenFile, 1);
			Grid.SetRow(_buttonOpenFile, 1);
			_buttonOpenFile.Content = horizontalStackPanel2;

			_textOpenFile = new TextBox();
			_textOpenFile.Id = "_textOpenFile";
			Grid.SetColumn(_textOpenFile, 2);
			Grid.SetRow(_textOpenFile, 1);

			var label5 = new Label();
			label5.Text = "Blue Button:";
			Grid.SetRow(label5, 2);

			_imageChooseFolder = new Image();
			_imageChooseFolder.Id = "_imageChooseFolder";

			var label6 = new Label();
			label6.Text = "Choose Folder";

			var horizontalStackPanel3 = new HorizontalStackPanel();
			horizontalStackPanel3.Widgets.Add(_imageChooseFolder);
			horizontalStackPanel3.Widgets.Add(label6);

			_buttonChooseFolder = new Button("blue");
			_buttonChooseFolder.Padding = new Thickness(8, 0);
			_buttonChooseFolder.Id = "_buttonChooseFolder";
			Grid.SetColumn(_buttonChooseFolder, 1);
			Grid.SetRow(_buttonChooseFolder, 2);
			_buttonChooseFolder.Content = horizontalStackPanel3;

			_textChooseFolder = new TextBox();
			_textChooseFolder.Id = "_textChooseFolder";
			Grid.SetColumn(_textChooseFolder, 2);
			Grid.SetRow(_textChooseFolder, 2);

			_textButtonLabel = new Label();
			_textButtonLabel.Text = "Text Button:";
			_textButtonLabel.Id = "_textButtonLabel";
			Grid.SetRow(_textButtonLabel, 3);

			var label7 = new Label();
			label7.Text = "Choose Color";

			_buttonChooseColor = new Button();
			_buttonChooseColor.Padding = new Thickness(8, 0);
			_buttonChooseColor.Id = "_buttonChooseColor";
			Grid.SetColumn(_buttonChooseColor, 1);
			Grid.SetRow(_buttonChooseColor, 3);
			_buttonChooseColor.Content = label7;

			var label8 = new Label();
			label8.Text = "Image Button:";
			Grid.SetRow(label8, 4);

			var image1 = new Image();

			_imageButton = new Button();
			_imageButton.Padding = new Thickness(8, 0);
			_imageButton.Id = "_imageButton";
			Grid.SetColumn(_imageButton, 1);
			Grid.SetRow(_imageButton, 4);
			_imageButton.Content = image1;

			var label9 = new Label();
			label9.Text = "This is checkbox";

			var checkButton1 = new CheckButton();
			checkButton1.CheckContentSpacing = 4;
			Grid.SetRow(checkButton1, 5);
			Grid.SetColumnSpan(checkButton1, 2);
			checkButton1.Content = label9;

			var label10 = new Label();
			label10.Text = "Horizontal Slider:";
			Grid.SetRow(label10, 6);

			var horizontalSlider1 = new HorizontalSlider();
			Grid.SetColumn(horizontalSlider1, 1);
			Grid.SetRow(horizontalSlider1, 6);
			Grid.SetColumnSpan(horizontalSlider1, 2);

			var label11 = new Label();
			label11.Text = "Combo View:";
			Grid.SetRow(label11, 7);

			var label12 = new Label();
			label12.Text = "Red";
			label12.TextColor = Color.Red;

			var label13 = new Label();
			label13.Text = "Green";
			label13.TextColor = Color.Lime;

			var label14 = new Label();
			label14.Text = "Blue";
			label14.TextColor = Color.Blue;

			var comboView1 = new ComboView();
			comboView1.Width = 200;
			Grid.SetColumn(comboView1, 1);
			Grid.SetRow(comboView1, 7);
			Grid.SetColumnSpan(comboView1, 2);
			comboView1.Widgets.Add(label12);
			comboView1.Widgets.Add(label13);
			comboView1.Widgets.Add(label14);

			var label15 = new Label();
			label15.Text = "Text Field:";
			Grid.SetRow(label15, 8);

			var textBox1 = new TextBox();
			Grid.SetColumn(textBox1, 1);
			Grid.SetRow(textBox1, 8);
			Grid.SetColumnSpan(textBox1, 2);

			var label16 = new Label();
			label16.Text = "Spin Button:";
			Grid.SetRow(label16, 9);

			var spinButton1 = new SpinButton();
			spinButton1.Value = 1;
			spinButton1.Width = 100;
			Grid.SetColumn(spinButton1, 1);
			Grid.SetRow(spinButton1, 9);

			var label17 = new Label();
			label17.Text = "List View:";
			Grid.SetRow(label17, 10);

			var label18 = new Label();
			label18.Text = "Red";
			label18.TextColor = Color.Red;

			var label19 = new Label();
			label19.Text = "Green";
			label19.TextColor = Color.Lime;

			var label20 = new Label();
			label20.Text = "Blue";
			label20.TextColor = Color.Blue;

			var listView1 = new ListView();
			listView1.Width = 200;
			Grid.SetColumn(listView1, 1);
			Grid.SetRow(listView1, 10);
			Grid.SetColumnSpan(listView1, 2);
			listView1.Widgets.Add(label18);
			listView1.Widgets.Add(label19);
			listView1.Widgets.Add(label20);

			var label21 = new Label();
			label21.Text = "Vertical Menu:";
			Grid.SetRow(label21, 11);

			var menuItem1 = new MenuItem();
			menuItem1.Text = "Start New Game";

			var menuItem2 = new MenuItem();
			menuItem2.Text = "Options";

			var menuItem3 = new MenuItem();
			menuItem3.Text = "Quit";

			var verticalMenu1 = new VerticalMenu();
			Grid.SetColumn(verticalMenu1, 1);
			Grid.SetRow(verticalMenu1, 11);
			verticalMenu1.Items.Add(menuItem1);
			verticalMenu1.Items.Add(menuItem2);
			verticalMenu1.Items.Add(menuItem3);

			var label22 = new Label();
			label22.Text = "Tree";
			Grid.SetRow(label22, 12);

			_gridRight = new Grid();
			_gridRight.ColumnSpacing = 8;
			_gridRight.RowSpacing = 8;
			_gridRight.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			_gridRight.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			_gridRight.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			_gridRight.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			_gridRight.Id = "_gridRight";
			_gridRight.Widgets.Add(label1);
			_gridRight.Widgets.Add(_buttonSaveFile);
			_gridRight.Widgets.Add(_textSaveFile);
			_gridRight.Widgets.Add(label3);
			_gridRight.Widgets.Add(_buttonOpenFile);
			_gridRight.Widgets.Add(_textOpenFile);
			_gridRight.Widgets.Add(label5);
			_gridRight.Widgets.Add(_buttonChooseFolder);
			_gridRight.Widgets.Add(_textChooseFolder);
			_gridRight.Widgets.Add(_textButtonLabel);
			_gridRight.Widgets.Add(_buttonChooseColor);
			_gridRight.Widgets.Add(label8);
			_gridRight.Widgets.Add(_imageButton);
			_gridRight.Widgets.Add(checkButton1);
			_gridRight.Widgets.Add(label10);
			_gridRight.Widgets.Add(horizontalSlider1);
			_gridRight.Widgets.Add(label11);
			_gridRight.Widgets.Add(comboView1);
			_gridRight.Widgets.Add(label15);
			_gridRight.Widgets.Add(textBox1);
			_gridRight.Widgets.Add(label16);
			_gridRight.Widgets.Add(spinButton1);
			_gridRight.Widgets.Add(label17);
			_gridRight.Widgets.Add(listView1);
			_gridRight.Widgets.Add(label21);
			_gridRight.Widgets.Add(verticalMenu1);
			_gridRight.Widgets.Add(label22);

			var scrollViewer1 = new ScrollViewer();
			scrollViewer1.ShowHorizontalScrollBar = false;
			scrollViewer1.Content = _gridRight;

			var label23 = new Label();
			label23.Text = "Vertical Slider:";

			var verticalSlider1 = new VerticalSlider();
			verticalSlider1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Grid.SetRow(verticalSlider1, 1);

			var grid1 = new Grid();
			grid1.RowSpacing = 8;
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid1.Widgets.Add(label23);
			grid1.Widgets.Add(verticalSlider1);

			var label24 = new Label();
			label24.Text = "Progress Bars:";

			_horizontalProgressBar = new HorizontalProgressBar();
			_horizontalProgressBar.Id = "_horizontalProgressBar";
			Grid.SetRow(_horizontalProgressBar, 1);

			_verticalProgressBar = new VerticalProgressBar();
			_verticalProgressBar.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_verticalProgressBar.Id = "_verticalProgressBar";
			Grid.SetRow(_verticalProgressBar, 2);

			var grid2 = new Grid();
			grid2.RowSpacing = 8;
			grid2.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid2.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid2.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid2.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid2.Widgets.Add(label24);
			grid2.Widgets.Add(_horizontalProgressBar);
			grid2.Widgets.Add(_verticalProgressBar);

			var verticalSplitPane1 = new VerticalSplitPane();
			verticalSplitPane1.Widgets.Add(grid1);
			verticalSplitPane1.Widgets.Add(grid2);

			var horizontalSplitPane1 = new HorizontalSplitPane();
			StackPanel.SetProportionType(horizontalSplitPane1, Myra.Graphics2D.UI.ProportionType.Fill);
			horizontalSplitPane1.Widgets.Add(scrollViewer1);
			horizontalSplitPane1.Widgets.Add(verticalSplitPane1);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(_mainMenu);
			verticalStackPanel1.Widgets.Add(horizontalSplitPane1);

			_labelOverGui = new Label();
			_labelOverGui.Text = "Is mouse over GUI: true";
			_labelOverGui.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			_labelOverGui.Id = "_labelOverGui";

			
			Widgets.Add(verticalStackPanel1);
			Widgets.Add(_labelOverGui);
		}

		
		public MenuItem _menuItemOpenFile;
		public MenuItem _menuItemSaveFile;
		public MenuItem _menuItemChooseFolder;
		public MenuItem _menuItemChooseColor;
		public MenuItem _menuItemQuit;
		public MenuItem _menuFile;
		public MenuItem _menuItemCopy;
		public MenuItem _menuItemPaste;
		public MenuItem _menuItemUndo;
		public MenuItem _menuItemRedo;
		public MenuItem _menuEdit;
		public MenuItem _menuItemAbout;
		public MenuItem _menuHelp;
		public HorizontalMenu _mainMenu;
		public Image _imageSaveFile;
		public Button _buttonSaveFile;
		public TextBox _textSaveFile;
		public Image _imageOpenFile;
		public Button _buttonOpenFile;
		public TextBox _textOpenFile;
		public Image _imageChooseFolder;
		public Button _buttonChooseFolder;
		public TextBox _textChooseFolder;
		public Label _textButtonLabel;
		public Button _buttonChooseColor;
		public Button _imageButton;
		public Grid _gridRight;
		public HorizontalProgressBar _horizontalProgressBar;
		public VerticalProgressBar _verticalProgressBar;
		public Label _labelOverGui;
	}
}
