name: Build & Publish Release

on: [workflow_dispatch]

jobs:
  BuildAndPublish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Build Myra.MonoGame
      run: dotnet build build\Myra.MonoGame.sln --configuration Release
    - name: Build Myra.Stride
      run: dotnet build build\Myra.Stride.sln --configuration Release
    - name: Build Myra.PlatformAgnostic
      run: dotnet build build\Myra.PlatformAgnostic.sln --configuration Release
    - name: Test
      run: dotnet test build\Myra.MonoGame.sln --verbosity normal
    - name: Install NuGet
      uses: NuGet/setup-nuget@v2
    - name: Publish Myra.MonoGame to MyGet
      run: nuget.exe push src\Myra\bin\MonoGame\Release\Myra.*.nupkg ${{secrets.MYGET_APIKEY}} -Source https://www.myget.org/F/abarim-games/api/v2/package
      continue-on-error: true
    - name: Publish Myra.PlatformAgnostic to MyGet
      run: nuget.exe push src\Myra\bin\PlatformAgnostic\Release\Myra.PlatformAgnostic.*.nupkg ${{secrets.MYGET_APIKEY}} -Source https://www.myget.org/F/abarim-games/api/v2/package
      continue-on-error: true
    - name: Publish Myra.MonoGame to NuGet
      run: nuget.exe push src\Myra\bin\MonoGame\Release\Myra.*.nupkg ${{secrets.NUGET_APIKEY}} -Source https://api.nuget.org/v3/index.json
      continue-on-error: true
    - name: Publish Myra.Stride to NuGet
      run: nuget.exe push src\Myra\bin\Stride\Release\Myra.Stride.*.nupkg ${{secrets.NUGET_APIKEY}} -Source https://api.nuget.org/v3/index.json
      continue-on-error: true
    - name: Publish Myra.PlatformAgnostic to NuGet
      run: nuget.exe push src\Myra\bin\PlatformAgnostic\Release\Myra.PlatformAgnostic.*.nupkg ${{secrets.NUGET_APIKEY}} -Source https://api.nuget.org/v3/index.json
      continue-on-error: true
    - name: Publish MyraPad to NuGet
      run: nuget.exe push src\MyraPad\bin\MonoGame\Release\myrapad.*.nupkg ${{secrets.NUGET_APIKEY}} -Source https://api.nuget.org/v3/index.json
      continue-on-error: true
    - name: Publish MyraViewer to NuGet
      run: nuget.exe push src\MyraViewer\bin\MonoGame\Release\myraviewer.*.nupkg ${{secrets.NUGET_APIKEY}} -Source https://api.nuget.org/v3/index.json
      continue-on-error: true
